export const BADGES = {
    // == BASE ==
    base_spectrum: { name: 'Base Spectrum', points: 1337, symbol: '🎨', desc: 'Part of the spectrum', rarity: 'Common' },

    // == MATHEMATICAL ==
    sum_even: { name: 'Even Steven', points: 2002, symbol: '⚖️', desc: 'Your color\'s energy is perfectly even.', rarity: 'Common' },
    sum_odd: { name: 'Oddball', points: 1999, symbol: '🎲', desc: 'Your color\'s energy is distinctly odd.', rarity: 'Common' },
    sum_div3: { name: 'Rule of Three', points: 15003, symbol: '3️⃣', desc: 'Your energy is a multiple of 3.', rarity: 'Uncommon' },
    sum_div9: { name: 'Triple Triple', points: 18009, symbol: '9️⃣', desc: 'Your energy is a multiple of 9.', rarity: 'Uncommon' },
    sum_div10: { name: 'Round Number', points: 10010, symbol: ' 🔟', desc: 'Your energy is a multiple of 10.', rarity: 'Uncommon' },
    sum_42: { name: 'Meaning of Life', points: 42069, symbol: '🧬', desc: 'Your energy is exactly 42.', rarity: 'Rare' },
    sum_100: { name: 'Century', points: 50011, symbol: '💯', desc: 'Your energy is exactly 100.', rarity: 'Rare' },
    sum_255: { name: 'Max Byte', points: 75031, symbol: '💾', desc: 'Your energy is exactly 255.', rarity: 'Rare' },
    sum_666: { name: 'Sinister Shade', points: 250001, symbol: '😈', desc: 'Your energy is exactly 666.', rarity: 'Epic' },
    sum_777: { name: 'Jackpot', points: 499999, symbol: '🎰', desc: 'Your energy is exactly 777.', rarity: 'Epic' },
    sum_fibonacci: { name: 'Golden Ratio', points: 100043, symbol: '🌀', desc: 'Your energy is a Fibonacci number.', rarity: 'Rare' },
    sum_square: { name: 'Perfect Square', points: 25047, symbol: '⏹️', desc: 'Your energy is a perfect square.', rarity: 'Uncommon' },
    sum_prime: { name: 'Prime Number', points: 100069, symbol: '🔢', desc: 'Your energy is a prime number.', rarity: 'Rare' },
    all_even: { name: 'All Even', points: 2222, symbol: '2️⃣', desc: 'All channels are even numbers.', rarity: 'Common' },
    all_odd: { name: 'All Odd', points: 3333, symbol: '1️⃣', desc: 'All channels are odd numbers.', rarity: 'Common' },
    mult_3: { name: 'Triple Threat', points: 4444, symbol: '🔢', desc: 'All channels are multiples of 3.', rarity: 'Common' },
    web_safe: { name: 'Web Safe', points: 15151, symbol: '🕸️', desc: 'A 1990s web safe color.', rarity: 'Uncommon' },
    mult_50: { name: 'Crisp Edges', points: 12500, symbol: '📐', desc: 'All channels are multiples of 50.', rarity: 'Uncommon' },
    one_is_loneliest: { name: 'One is the Loneliest', points: 55001, symbol: '1️⃣', desc: 'One channel is exactly 1.', rarity: 'Rare' },
    twin_channels: { name: 'Twin Channels', points: 6601, symbol: '👯', desc: 'Two channels share the exact same value.', rarity: 'Common' },

    // == COLOR THEORY & BRIGHTNESS ==
    high_contrast: { name: 'High Contrast', points: 8080, symbol: '🌓', desc: 'Your channels are wildly divergent.', rarity: 'Uncommon' },
    low_contrast: { name: 'Low Contrast', points: 1111, symbol: '🌫️', desc: 'A muddy or muted tone.', rarity: 'Common' },
    mod_contrast: { name: 'Moderate Contrast', points: 3300, symbol: '🛤️', desc: 'A balanced range of energy.', rarity: 'Common' },
    pastel_soft: { name: 'Pastel Soft', points: 250001, symbol: '🌸', desc: 'A soft pastel hue.', rarity: 'Epic' },
    neon_bright: { name: 'Neon Bright', points: 250003, symbol: '💡', desc: 'A vivid neon glow.', rarity: 'Epic' },
    neon_glow: { name: 'Neon Glow', points: 499997, symbol: '☢️', desc: 'One channel maxed, others near zero.', rarity: 'Epic' },
    pastel_dream: { name: 'Pastel Dream', points: 100043, symbol: '🛌', desc: 'All channels are very bright.', rarity: 'Rare' },
    deep_shadow: { name: 'Deep Shadow', points: 50021, symbol: '🌑', desc: 'All channels are very dark.', rarity: 'Rare' },
    high_roller: { name: 'High Roller', points: 250069, symbol: '🎰', desc: 'All channels are above 200.', rarity: 'Epic' },
    bright_red: { name: 'Bright Red', points: 4400, symbol: '🔴', desc: 'Red channel is radiating bright energy.', rarity: 'Common' },
    dark_red: { name: 'Dark Red', points: 2200, symbol: '🔴', desc: 'Red channel is cloaked in shadow.', rarity: 'Common' },
    bright_green: { name: 'Bright Green', points: 4400, symbol: '🟢', desc: 'Green channel is radiating bright energy.', rarity: 'Common' },
    dark_green: { name: 'Dark Green', points: 2200, symbol: '🟢', desc: 'Green channel is cloaked in shadow.', rarity: 'Common' },
    bright_blue: { name: 'Bright Blue', points: 4400, symbol: '🔵', desc: 'Blue channel is radiating bright energy.', rarity: 'Common' },
    dark_blue: { name: 'Dark Blue', points: 2200, symbol: '🔵', desc: 'Blue channel is cloaked in shadow.', rarity: 'Common' },
    greyscale: { name: 'Greyscale', points: 25525, symbol: '⚫', desc: 'All channels are identical.', rarity: 'Uncommon' },
    monochromatic: { name: 'Monochromatic', points: 15001, symbol: '🎛️', desc: 'Channels are within 15 points.', rarity: 'Uncommon' },
    warm_tone: { name: 'Warm Tone', points: 1100, symbol: '🔥', desc: 'Red is your dominant channel.', rarity: 'Common' },
    cool_tone: { name: 'Cool Tone', points: 1100, symbol: '🧊', desc: 'Blue is your dominant channel.', rarity: 'Common' },
    ascending: { name: 'Ascending', points: 3301, symbol: '📈', desc: 'Red < Green < Blue.', rarity: 'Common' },
    descending: { name: 'Descending', points: 3301, symbol: '📉', desc: 'Red > Green > Blue.', rarity: 'Common' },
    symmetrical: { name: 'Symmetrical', points: 7700, symbol: '🦋', desc: 'Red and Blue channels are identical.', rarity: 'Uncommon' },

    // == HEX PATTERNS ==
    palindrome: { name: 'Palindrome', points: 50005, symbol: '🪞', desc: 'Reads the same backwards.', rarity: 'Rare' },
    perfect_triplets: { name: 'Perfect Triplets', points: 150000, symbol: '🟰', desc: 'Hex is XXYYZZ.', rarity: 'Rare' },
    the_light: { name: 'The Light', points: 2500000, symbol: '☀️', desc: 'Pure White (#FFFFFF).', rarity: 'Mythic' },
    the_void: { name: 'The Void', points: 2500000, symbol: '🌑', desc: 'Pure Black (#000000).', rarity: 'Mythic' },
    contains_a: { name: 'A is for Apple', points: 4111, symbol: '🅰️', desc: 'Hex contains A.', rarity: 'Common' },
    contains_b: { name: 'B is for Bee', points: 4222, symbol: '🅱️', desc: 'Hex contains B.', rarity: 'Common' },
    contains_c: { name: 'C is for Sea', points: 4333, symbol: ' ©️', desc: 'Hex contains C.', rarity: 'Common' },
    contains_d: { name: 'D is for Dog', points: 4444, symbol: '🇩', desc: 'Hex contains D.', rarity: 'Common' },
    contains_e: { name: 'E is for Elephant', points: 4555, symbol: '📧', desc: 'Hex contains E.', rarity: 'Common' },
    contains_f: { name: 'F is for Fox', points: 4666, symbol: '🇫', desc: 'Hex contains F.', rarity: 'Common' },
    contains_0: { name: 'Zero Hero', points: 4000, symbol: '⭕', desc: 'Hex contains 0.', rarity: 'Common' },
    contains_1: { name: 'One is Fun', points: 4111, symbol: '1️⃣', desc: 'Hex contains 1.', rarity: 'Common' },
    contains_2: { name: 'Two is True', points: 4222, symbol: '2️⃣', desc: 'Hex contains 2.', rarity: 'Common' },
    contains_3: { name: 'Three is Free', points: 4333, symbol: '3️⃣', desc: 'Hex contains 3.', rarity: 'Common' },
    contains_4: { name: 'Four is Door', points: 4444, symbol: '4️⃣', desc: 'Hex contains 4.', rarity: 'Common' },
    contains_5: { name: 'Five is Alive', points: 4555, symbol: '5️⃣', desc: 'Hex contains 5.', rarity: 'Common' },
    contains_6: { name: 'Six is Kicks', points: 4666, symbol: '6️⃣', desc: 'Hex contains 6.', rarity: 'Common' },
    contains_7: { name: 'Seven is Heaven', points: 4777, symbol: '7️⃣', desc: 'Hex contains 7.', rarity: 'Common' },
    contains_8: { name: 'Eight is Great', points: 4888, symbol: '8️⃣', desc: 'Hex contains 8.', rarity: 'Common' },
    contains_9: { name: 'Nine is Fine', points: 4999, symbol: '9️⃣', desc: 'Hex contains 9.', rarity: 'Common' },
    contains_00: { name: 'Double Zero', points: 8008, symbol: ' 👀', desc: 'Hex contains 00.', rarity: 'Common' },
    contains_11: { name: 'Double One', points: 1111, symbol: '11', desc: 'Hex contains 11.', rarity: 'Common' },
    contains_22: { name: 'Double Two', points: 2222, symbol: '22', desc: 'Hex contains 22.', rarity: 'Common' },
    contains_33: { name: 'Double Three', points: 3333, symbol: '33', desc: 'Hex contains 33.', rarity: 'Common' },
    contains_44: { name: 'Double Four', points: 4444, symbol: '44', desc: 'Hex contains 44.', rarity: 'Common' },
    contains_55: { name: 'Double Five', points: 5555, symbol: '55', desc: 'Hex contains 55.', rarity: 'Common' },
    contains_66: { name: 'Double Six', points: 6666, symbol: '66', desc: 'Hex contains 66.', rarity: 'Common' },
    contains_77: { name: 'Double Seven', points: 7777, symbol: '77', desc: 'Hex contains 77.', rarity: 'Common' },
    contains_88: { name: 'Double Eight', points: 8888, symbol: '88', desc: 'Hex contains 88.', rarity: 'Common' },
    contains_99: { name: 'Double Nine', points: 9999, symbol: '99', desc: 'Hex contains 99.', rarity: 'Common' },
    contains_aa: { name: 'Double A', points: 10001, symbol: 'AA', desc: 'Hex contains AA.', rarity: 'Uncommon' },
    contains_bb: { name: 'Double B', points: 11011, symbol: 'BB', desc: 'Hex contains BB.', rarity: 'Uncommon' },
    contains_cc: { name: 'Double C', points: 12021, symbol: 'CC', desc: 'Hex contains CC.', rarity: 'Uncommon' },
    contains_dd: { name: 'Double D', points: 13031, symbol: 'DD', desc: 'Hex contains DD.', rarity: 'Uncommon' },
    contains_ee: { name: 'Double E', points: 14041, symbol: 'EE', desc: 'Hex contains EE.', rarity: 'Uncommon' },
    contains_ff: { name: 'Double F', points: 15051, symbol: 'FF', desc: 'Hex contains FF.', rarity: 'Uncommon' },
    contains_000: { name: 'Triple Zero', points: 50000, symbol: '000', desc: 'Hex contains 000.', rarity: 'Rare' },
    contains_111: { name: 'Triple One', points: 11111, symbol: '111', desc: 'Hex contains 111.', rarity: 'Uncommon' },
    contains_222: { name: 'Triple Two', points: 22222, symbol: '222', desc: 'Hex contains 222.', rarity: 'Uncommon' },
    contains_333: { name: 'Triple Three', points: 33333, symbol: '333', desc: 'Hex contains 333.', rarity: 'Uncommon' },
    contains_444: { name: 'Triple Four', points: 44444, symbol: '444', desc: 'Hex contains 444.', rarity: 'Uncommon' },
    contains_555: { name: 'Triple Five', points: 55555, symbol: '555', desc: 'Hex contains 555.', rarity: 'Uncommon' },
    contains_666: { name: 'Triple Six', points: 66666, symbol: '666', desc: 'Hex contains 666.', rarity: 'Uncommon' },
    contains_777: { name: 'Triple Seven', points: 77777, symbol: '777', desc: 'Hex contains 777.', rarity: 'Uncommon' },
    contains_888: { name: 'Triple Eight', points: 88888, symbol: '888', desc: 'Hex contains 888.', rarity: 'Uncommon' },
    contains_999: { name: 'Triple Nine', points: 99999, symbol: '999', desc: 'Hex contains 999.', rarity: 'Uncommon' },
    contains_aaa: { name: 'Triple A', points: 100001, symbol: 'AAA', desc: 'Hex contains AAA.', rarity: 'Rare' },
    contains_bbb: { name: 'Triple B', points: 110011, symbol: 'BBB', desc: 'Hex contains BBB.', rarity: 'Rare' },
    contains_ccc: { name: 'Triple C', points: 120021, symbol: 'CCC', desc: 'Hex contains CCC.', rarity: 'Rare' },
    contains_ddd: { name: 'Triple D', points: 130031, symbol: 'DDD', desc: 'Hex contains DDD.', rarity: 'Rare' },
    contains_eee: { name: 'Triple E', points: 140041, symbol: 'EEE', desc: 'Hex contains EEE.', rarity: 'Rare' },
    contains_fff: { name: 'Triple F', points: 150051, symbol: 'FFF', desc: 'Hex contains FFF.', rarity: 'Rare' },

    // == MEME & POP CULTURE ==
    dead: { name: 'Dead Man Walking', points: 73217, symbol: '💀', desc: 'Hex contains DEAD.', rarity: 'Rare' },
    beef: { name: 'Where is the Beef?', points: 83388, symbol: '🥩', desc: 'Hex contains BEEF.', rarity: 'Rare' },
    cafe: { name: 'Coffee Break', points: 74237, symbol: '☕', desc: 'Hex contains CAFE.', rarity: 'Rare' },
    face: { name: 'Face Value', points: 42069, symbol: '😎', desc: 'Hex contains FACE.', rarity: 'Rare' },
    babe: { name: 'Babe', points: 80085, symbol: '👶', desc: 'Hex contains BABE.', rarity: 'Rare' },
    fade: { name: 'Fade', points: 69696, symbol: '🕳️', desc: 'Hex contains FADE.', rarity: 'Rare' },
    feed: { name: 'Feed', points: 133735, symbol: '🍼', desc: 'Hex contains FEED.', rarity: 'Rare' },
    boob: { name: 'Boob', points: 80085, symbol: '🍒', desc: 'Hex contains B00B.', rarity: 'Rare' },
    dood: { name: 'Dood', points: 42042, symbol: '🧑‍🎨', desc: 'Hex contains D00D.', rarity: 'Rare' },
    food: { name: 'Food', points: 42042, symbol: '🍔', desc: 'Hex contains F00D.', rarity: 'Rare' },
    leet: { name: 'Leet Speak', points: 133713, symbol: '💻', desc: 'Hex contains 1337.', rarity: 'Rare' },
    boob_2: { name: 'Boob 2', points: 80085, symbol: '🍈', desc: 'Hex contains 8008.', rarity: 'Rare' },
    abcd: { name: 'Alphabetical', points: 12345, symbol: '🔤', desc: 'Hex contains ABCD.', rarity: 'Uncommon' },
    james_bond: { name: 'James Bond', points: 70007, symbol: '🕵️', desc: 'Hex contains 007.', rarity: 'Rare' },
    blaze_it: { name: 'Blaze It', points: 42069, symbol: '🌿', desc: 'Hex contains 420.', rarity: 'Rare' },
    nice: { name: 'Nice', points: 6969, symbol: '😏', desc: 'Hex contains 69.', rarity: 'Uncommon' },
    demon: { name: 'Demon', points: 66666, symbol: '😈', desc: 'Hex contains 666.', rarity: 'Uncommon' },
    jackpot: { name: 'Jackpot', points: 77777, symbol: '🎰', desc: 'Hex contains 777.', rarity: 'Uncommon' },
    emergency: { name: 'Emergency', points: 91101, symbol: '🚨', desc: 'Hex contains 911.', rarity: 'Rare' },
    not_found: { name: 'Not Found', points: 40404, symbol: '🚫', desc: 'Hex contains 404.', rarity: 'Uncommon' },
    server_error: { name: 'Server Error', points: 50000, symbol: '⚠️', desc: 'Hex contains 500.', rarity: 'Uncommon' },
    perfect_score: { name: 'Perfect Score', points: 100000, symbol: '💯', desc: 'Hex contains 100.', rarity: 'Rare' },
    f1: { name: 'Formula 1', points: 1000001, symbol: '🏎️', desc: 'Hex contains F1.', rarity: 'Epic' },

    // == PURE COLORS & BRANDS ==
    pure_red: { name: 'Maximum Red', points: 666666, symbol: '🟥', desc: 'Pure Red (255,0,0).', rarity: 'Epic' },
    pure_green: { name: 'Maximum Green', points: 999999, symbol: '🟩', desc: 'Pure Green (0,255,0).', rarity: 'Epic' },
    pure_blue: { name: 'Maximum Blue', points: 420420, symbol: '🟦', desc: 'Pure Blue (0,0,255).', rarity: 'Epic' },
    gold: { name: 'Midas', points: 1500000, symbol: '🥇', desc: 'Pure Gold (255,215,0).', rarity: 'Mythic' },
    streamer_purple: { name: 'Streamer Purple', points: 1000000, symbol: '🟣', desc: 'Brand Match (145,70,255).', rarity: 'Mythic' },
    audio_stream_green: { name: 'Audio Stream Green', points: 1000000, symbol: '🟢', desc: 'Brand Match (30,215,96).', rarity: 'Mythic' },
    classic_cola_red: { name: 'Classic Cola Red', points: 1000000, symbol: '🥤', desc: 'Brand Match (244,0,9).', rarity: 'Mythic' },

    // == SPECIAL EDGE CASES ==
    almost_black: { name: 'Almost Black', points: 1000000, symbol: '🌑', desc: 'So close to the void (0,0,1).', rarity: 'Mythic' },
    almost_white: { name: 'Almost White', points: 1000000, symbol: '☀️', desc: 'So close to the light (255,255,254).', rarity: 'Mythic' },
    perfect_grey: { name: 'Perfect Grey', points: 127000, symbol: '🔘', desc: 'Exactly middle grey (127,127,127).', rarity: 'Rare' },

    // == SYSTEM / EVENT BADGES ==
    streak_bonus_7: { name: '7-Day Streak Bonus', points: 50000, symbol: '🔥', desc: '7 days in a row!', rarity: 'Epic' },
    reroll_shard_earned: { name: 'Reroll Shard Earned', points: 0, symbol: '🎲', desc: 'Can be used to reroll a bad daily score!', rarity: 'Epic' },
    milestone_30: { name: 'Milestone Reward!', points: 0, symbol: '🎁', desc: 'Unlocked the Monthly Grinder Frame!', rarity: 'Mythic' },
    milestone_100: { name: 'Milestone Reward!', points: 0, symbol: '🎁', desc: 'Unlocked the Iron Will Frame!', rarity: 'Mythic' },
    milestone_365: { name: 'Milestone Reward!', points: 0, symbol: '🎁', desc: 'Unlocked the Annual Frame!', rarity: 'Mythic' },
    beat_your_best: { name: 'Beat Your Best!', points: 50000, symbol: '🚀', desc: 'New personal record!', rarity: 'Epic' },
    cotw_hit: { name: 'Color of the Week!', points: 50000, symbol: '🎯', desc: 'Matched the weekly target color!', rarity: 'Epic' }
};

export const ACHIEVEMENTS = {
    first_roll: { name: 'Achievement: First Steps', points: 1000, symbol: '🎲', desc: 'Roll the die for the first time.', rarity: 'Mythic' },
    roll_10: { name: 'Achievement: Dedicated', points: 10000, symbol: '🧡', desc: 'Roll the die 10 times.', rarity: 'Mythic' },
    roll_50: { name: 'Achievement: Veteran', points: 100000, symbol: '💜', desc: 'Roll the die 50 times.', rarity: 'Mythic' },
    roll_100: { name: 'Achievement: Centurion', points: 250000, symbol: '💯', desc: 'Roll the die 100 times.', rarity: 'Mythic' },
    roll_365: { name: 'Achievement: Annual', points: 1000000, symbol: '📅', desc: 'Roll the die 365 times.', rarity: 'Mythic' },
    streak_7: { name: 'Achievement: Week Warrior', points: 50000, symbol: '🔥', desc: 'Maintain a 7-day streak.', rarity: 'Mythic' },
    streak_14: { name: 'Achievement: Fortnight', points: 100000, symbol: '🔥', desc: 'Maintain a 14-day streak.', rarity: 'Mythic' },
    streak_30: { name: 'Achievement: Monthly Grinder', points: 500000, symbol: '📅', desc: 'Maintain a 30-day streak.', rarity: 'Mythic' },
    streak_100: { name: 'Achievement: Iron Will', points: 2000000, symbol: '🔥', desc: 'Maintain a 100-day streak.', rarity: 'Mythic' },
    score_10k: { name: 'Achievement: Five Digits', points: 10000, symbol: '💰', desc: 'Score over 10,000 EP in a single roll.', rarity: 'Mythic' },
    score_50k: { name: 'Achievement: High Roller', points: 50000, symbol: '💰', desc: 'Score over 50,000 EP in a single roll.', rarity: 'Mythic' },
    score_100k: { name: 'Achievement: Six Digits', points: 100000, symbol: '💰', desc: 'Score over 100,000 EP in a single roll.', rarity: 'Mythic' },
    score_1m: { name: 'Achievement: Millionaire', points: 250000, symbol: '💰', desc: 'Score over 1,000,000 EP in a single roll.', rarity: 'Mythic' },
    score_5m: { name: 'Achievement: Tycoon', points: 1000000, symbol: '💰', desc: 'Score over 5,000,000 EP in a single roll.', rarity: 'Mythic' },
    rarity_rare: { name: 'Achievement: Uncommonly Rare', points: 25000, symbol: '🔵', desc: 'Roll a Rare rarity color.', rarity: 'Mythic' },
    rarity_epic: { name: 'Achievement: Epic Encounter', points: 100000, symbol: '🟣', desc: 'Roll an Epic rarity color.', rarity: 'Mythic' },
    rarity_anomaly: { name: 'Achievement: Anomaly Detected', points: 500000, symbol: '🟠', desc: 'Roll an Anomaly rarity color.', rarity: 'Mythic' },
    mythic_roll: { name: 'Achievement: Mythic Touch', points: 1000000, symbol: '🌟', desc: 'Roll a Mythic rarity color.', rarity: 'Mythic' },
    roll_even_sum: { name: 'Achievement: Even Steven', points: 5000, symbol: '⚖️', desc: 'Roll a color with an even R+G+B sum.', rarity: 'Mythic' },
    roll_odd_sum: { name: 'Achievement: Oddball', points: 5000, symbol: '🎲', desc: 'Roll a color with an odd R+G+B sum.', rarity: 'Mythic' },
    roll_div3_sum: { name: 'Achievement: Rule of Three', points: 15000, symbol: '3️⃣', desc: 'Roll a color where R+G+B is divisible by 3.', rarity: 'Mythic' },
    roll_42_sum: { name: 'Achievement: Meaning of Life', points: 42000, symbol: '🧬', desc: 'Roll a color where R+G+B is exactly 42.', rarity: 'Mythic' },
    roll_balanced_sum: { name: 'Achievement: Balanced', points: 10000, symbol: '🧘', desc: 'Roll a color where R+G+B is between 300 and 499.', rarity: 'Mythic' },
    roll_prime: { name: 'Achievement: Prime Number', points: 100000, symbol: '🔢', desc: 'Roll a color with a prime R+G+B sum.', rarity: 'Mythic' },
    all_even_rgb: { name: 'Achievement: All Even', points: 15000, symbol: '2️⃣', desc: 'Roll a color where R, G, and B are all even numbers.', rarity: 'Mythic' },
    all_odd_rgb: { name: 'Achievement: All Odd', points: 15000, symbol: '1️⃣', desc: 'Roll a color where R, G, and B are all odd numbers.', rarity: 'Mythic' },
    mult_3_rgb: { name: 'Achievement: Triple Threat', points: 25000, symbol: '🔢', desc: 'Roll a color where R, G, and B are all multiples of 3.', rarity: 'Mythic' },
    high_contrast: { name: 'Achievement: High Contrast', points: 25000, symbol: '🌓', desc: 'Roll a color with an extreme RGB range (>200).', rarity: 'Mythic' },
    low_contrast: { name: 'Achievement: Low Contrast', points: 10000, symbol: '🌫️', desc: 'Roll a color with a muddy/muted RGB range (<50).', rarity: 'Mythic' },
    mod_contrast: { name: 'Achievement: Moderate Contrast', points: 15000, symbol: '🛤️', desc: 'Roll a color with an RGB range between 50 and 150.', rarity: 'Mythic' },
    pastel_soft: { name: 'Achievement: Pastel Soft', points: 200000, symbol: '🌸', desc: 'Roll a soft pastel hue.', rarity: 'Mythic' },
    neon_bright: { name: 'Achievement: Neon Bright', points: 200000, symbol: '💡', desc: 'Roll a vivid neon glow.', rarity: 'Mythic' },
    web_safe: { name: 'Achievement: Web Safe', points: 30000, symbol: '🕸️', desc: 'Roll a 1990s web safe color.', rarity: 'Mythic' },
    roll_palindrome: { name: 'Achievement: Mirror', points: 100000, symbol: '🪞', desc: 'Roll a hex palindrome (reads same backwards).', rarity: 'Mythic' },
    perfect_triplets: { name: 'Achievement: Perfect Triplets', points: 150000, symbol: '🟰', desc: 'Roll a hex that is XXYYZZ.', rarity: 'Mythic' },
    greyscale: { name: 'Achievement: Greyscale', points: 30000, symbol: '⚫', desc: 'Roll a pure greyscale color.', rarity: 'Mythic' },
    hex_letters: { name: 'Achievement: Alphabet Soup', points: 500000, symbol: '🔤', desc: 'Roll a hex containing all 6 letters (A-F).', rarity: 'Mythic' },
    contains_a: { name: 'Achievement: A is for Apple', points: 5000, symbol: '🅰️', desc: 'Roll a hex containing A.', rarity: 'Mythic' },
    contains_b: { name: 'Achievement: B is for Bee', points: 5000, symbol: '🅱️', desc: 'Roll a hex containing B.', rarity: 'Mythic' },
    contains_c: { name: 'Achievement: C is for Sea', points: 5000, symbol: '©️', desc: 'Roll a hex containing C.', rarity: 'Mythic' },
    contains_d: { name: 'Achievement: D is for Dog', points: 5000, symbol: '🇩', desc: 'Roll a hex containing D.', rarity: 'Mythic' },
    contains_e: { name: 'Achievement: E is for Elephant', points: 5000, symbol: '📧', desc: 'Roll a hex containing E.', rarity: 'Mythic' },
    contains_f: { name: 'Achievement: F is for Fox', points: 5000, symbol: '🇫', desc: 'Roll a hex containing F.', rarity: 'Mythic' },
    contains_0: { name: 'Achievement: Zero Hero', points: 5000, symbol: '⭕', desc: 'Roll a hex containing 0.', rarity: 'Mythic' },
    roll_black: { name: 'Achievement: The Void', points: 5000000, symbol: '🌑', desc: 'Roll Pure Black (#000000).', rarity: 'Mythic' },
    roll_white: { name: 'Achievement: The Light', points: 5000000, symbol: '☀️', desc: 'Roll Pure White (#FFFFFF).', rarity: 'Mythic' },
    roll_gold: { name: 'Achievement: Midas', points: 2000000, symbol: '🥇', desc: 'Roll Pure Gold.', rarity: 'Mythic' },
    pure_red: { name: 'Achievement: Maximum Red', points: 500000, symbol: '🟥', desc: 'Roll Pure Red (255,0,0).', rarity: 'Mythic' },
    pure_green: { name: 'Achievement: Maximum Green', points: 500000, symbol: '🟩', desc: 'Roll Pure Green (0,255,0).', rarity: 'Mythic' },
    pure_blue: { name: 'Achievement: Maximum Blue', points: 500000, symbol: '🟦', desc: 'Roll Pure Blue (0,0,255).', rarity: 'Mythic' },
    streamer_purple: { name: 'Achievement: Streamer Purple', points: 2000000, symbol: '🟣', desc: 'Roll Streamer Purple.', rarity: 'Mythic' },
    audio_stream_green: { name: 'Achievement: Audio Stream Green', points: 2000000, symbol: '🟢', desc: 'Roll Audio Stream Green.', rarity: 'Mythic' },
    classic_cola_red: { name: 'Achievement: Classic Cola Red', points: 2000000, symbol: '🥤', desc: 'Roll Classic Cola Red.', rarity: 'Mythic' },
    roll_beef: { name: 'Achievement: Where is the Beef?', points: 50000, symbol: '🥩', desc: 'Roll a hex containing BEEF.', rarity: 'Mythic' },
    roll_cafe: { name: 'Achievement: Coffee Break', points: 50000, symbol: '☕', desc: 'Roll a hex containing CAFE.', rarity: 'Mythic' },
    roll_dead: { name: 'Achievement: Dead Man Walking', points: 50000, symbol: '💀', desc: 'Roll a hex containing DEAD.', rarity: 'Mythic' },
    roll_face: { name: 'Achievement: Face Value', points: 50000, symbol: '😎', desc: 'Roll a hex containing FACE.', rarity: 'Mythic' },
    launch_adopter: { name: 'Achievement: Launch Day Adopter', points: 100000, symbol: '🚀', desc: 'Roll the die during the official launch window.', rarity: 'Mythic' }
};

export const CANDIDATE_ACHIEVEMENTS = {
    first_roll: { name: 'Achievement: First Steps', points: 5000, symbol: '🎲', desc: 'Roll the die for the first time.', rarity: 'Common' },
    roll_10: { name: 'Achievement: Dedicated', points: 25000, symbol: '🧡', desc: 'Roll the die 10 times.', rarity: 'Common' },
    roll_50: { name: 'Achievement: Veteran', points: 100000, symbol: '💜', desc: 'Roll the die 50 times.', rarity: 'Rare' },
    roll_100: { name: 'Achievement: Centurion', points: 250000, symbol: '💯', desc: 'Roll the die 100 times.', rarity: 'Epic' },
    roll_365: { name: 'Achievement: Annual', points: 1000000, symbol: '📅', desc: 'Roll the die 365 times.', rarity: 'Mythic' },
    streak_7: { name: 'Achievement: Week Warrior', points: 50000, symbol: '🔥', desc: 'Maintain a 7-day streak.', rarity: 'Common' },
    streak_14: { name: 'Achievement: Fortnight', points: 100000, symbol: '🔥', desc: 'Maintain a 14-day streak.', rarity: 'Rare' },
    streak_30: { name: 'Achievement: Monthly Grinder', points: 250000, symbol: '📅', desc: 'Maintain a 30-day streak.', rarity: 'Epic' },
    streak_100: { name: 'Achievement: Iron Will', points: 750000, symbol: '🔥', desc: 'Maintain a 100-day streak.', rarity: 'Mythic' },
    rarity_rare: { name: 'Achievement: Uncommonly Rare', points: 25000, symbol: '🔵', desc: 'Roll a Rare color.', rarity: 'Common' },
    rarity_epic: { name: 'Achievement: Epic Encounter', points: 100000, symbol: '🟣', desc: 'Roll an Epic color.', rarity: 'Rare' },
    rarity_anomaly: { name: 'Achievement: Anomaly Detected', points: 250000, symbol: '🟠', desc: 'Roll an Anomaly color.', rarity: 'Epic' },
    mythic_roll: { name: 'Achievement: Mythic Touch', points: 500000, symbol: '🌟', desc: 'Roll a Mythic color.', rarity: 'Mythic' },
    score_50k: { name: 'Achievement: High Roller', points: 25000, symbol: '💰', desc: 'Score at least 50,000 EP in a single roll.', rarity: 'Common' },
    score_100k: { name: 'Achievement: Six Digits', points: 100000, symbol: '💰', desc: 'Score at least 100,000 EP in a single roll.', rarity: 'Rare' },
    score_200k: { name: 'Achievement: Anomaly Hunter', points: 250000, symbol: '💰', desc: 'Score at least 200,000 EP in a single roll.', rarity: 'Epic' },
    score_1_5m: { name: 'Achievement: Once in a Spectrum', points: 500000, symbol: '🌈', desc: 'Score at least 1,500,000 EP in a single roll.', rarity: 'Mythic' },
    roll_prime: { name: 'Achievement: Prime Number', points: 25000, symbol: '🔢', desc: 'Roll a color with a prime RGB sum.', rarity: 'Common' },
    high_contrast: { name: 'Achievement: Polarized Channels', points: 25000, symbol: '🌓', desc: 'Roll a color with an extreme RGB range.', rarity: 'Common' },
    low_contrast: { name: 'Achievement: Close Harmony', points: 15000, symbol: '🌫️', desc: 'Roll a color with very close RGB channels.', rarity: 'Common' },
    greyscale: { name: 'Achievement: Perfect Greyscale', points: 50000, symbol: '⚫', desc: 'Roll a pure greyscale color.', rarity: 'Rare' },
    web_safe: { name: 'Achievement: Web Safe', points: 50000, symbol: '🕸️', desc: 'Roll a classic web-safe color.', rarity: 'Rare' },
    roll_42_sum: { name: 'Achievement: Meaning of Life', points: 100000, symbol: '🧬', desc: 'Roll a color where R+G+B is exactly 42.', rarity: 'Rare' },
    roll_beef: { name: 'Achievement: Where is the Beef?', points: 100000, symbol: '🥩', desc: 'Roll a hex containing BEEF.', rarity: 'Rare' },
    roll_cafe: { name: 'Achievement: Coffee Break', points: 100000, symbol: '☕', desc: 'Roll a hex containing CAFE.', rarity: 'Rare' },
    roll_dead: { name: 'Achievement: Dead Man Walking', points: 100000, symbol: '💀', desc: 'Roll a hex containing DEAD.', rarity: 'Rare' },
    roll_face: { name: 'Achievement: Face Value', points: 100000, symbol: '😎', desc: 'Roll a hex containing FACE.', rarity: 'Rare' },
    roll_palindrome: { name: 'Achievement: Mirror', points: 150000, symbol: '🪞', desc: 'Roll a hex palindrome.', rarity: 'Epic' },
    repeated_pair: { name: 'Achievement: Repeated Pair', points: 125000, symbol: '🟰', desc: 'Roll a hex that repeats the same byte three times.', rarity: 'Epic' },
    saturation_spike: { name: 'Achievement: Saturation Spike', points: 50000, symbol: '🎨', desc: 'Roll an extremely saturated color.', rarity: 'Rare' },
    triple_crown: { name: 'Achievement: Triple Crown', points: 150000, symbol: '👑', desc: 'Roll one low, one middle, and one maximum channel.', rarity: 'Epic' },
    pastel_soft: { name: 'Achievement: Pastel Bloom', points: 50000, symbol: '🌸', desc: 'Roll a bright, soft pastel color.', rarity: 'Rare' },
    neon_bright: { name: 'Achievement: Neon Voltage', points: 50000, symbol: '💡', desc: 'Roll a vivid high-contrast color.', rarity: 'Rare' },
    roll_black: { name: 'Achievement: The Void', points: 500000, symbol: '🌑', desc: 'Roll Pure Black (#000000).', rarity: 'Mythic' },
    roll_white: { name: 'Achievement: The Light', points: 500000, symbol: '☀️', desc: 'Roll Pure White (#FFFFFF).', rarity: 'Mythic' },
    roll_gold: { name: 'Achievement: Midas', points: 500000, symbol: '🥇', desc: 'Roll Pure Gold (#FFD700).', rarity: 'Mythic' },
    pure_red: { name: 'Achievement: Maximum Red', points: 250000, symbol: '🟥', desc: 'Roll Pure Red (#FF0000).', rarity: 'Epic' },
    pure_green: { name: 'Achievement: Maximum Green', points: 250000, symbol: '🟩', desc: 'Roll Pure Green (#00FF00).', rarity: 'Epic' },
    pure_blue: { name: 'Achievement: Maximum Blue', points: 250000, symbol: '🟦', desc: 'Roll Pure Blue (#0000FF).', rarity: 'Epic' },
    streamer_purple: { name: 'Achievement: Streamer Purple', points: 350000, symbol: '🟣', desc: 'Roll Streamer Purple.', rarity: 'Mythic' },
    audio_stream_green: { name: 'Achievement: Audio Stream Green', points: 350000, symbol: '🟢', desc: 'Roll Audio Stream Green.', rarity: 'Mythic' },
    classic_cola_red: { name: 'Achievement: Classic Cola Red', points: 350000, symbol: '🥤', desc: 'Roll Classic Cola Red.', rarity: 'Mythic' }
};

export const CANDIDATE_BADGES = {
    sum_42: { name: 'Meaning of Life', points: 150042, symbol: '🧬', desc: 'Your RGB sum is exactly 42.', rarity: 'Epic' },
    sum_100: { name: 'Perfect Century', points: 100100, symbol: '💯', desc: 'Your RGB sum is exactly 100.', rarity: 'Rare' },
    sum_255: { name: 'Max Byte', points: 75255, symbol: '💾', desc: 'Your RGB sum is exactly 255.', rarity: 'Rare' },
    sum_666: { name: 'Sinister Shade', points: 250666, symbol: '😈', desc: 'Your RGB sum is exactly 666.', rarity: 'Epic' },
    high_contrast: { name: 'Polarized Channels', points: 18205, symbol: '🌓', desc: 'Your channel range is extremely wide.', rarity: 'Uncommon' },
    low_contrast: { name: 'Close Harmony', points: 12020, symbol: '🌫️', desc: 'Your channels sit close together.', rarity: 'Common' },
    greyscale: { name: 'Perfect Greyscale', points: 75256, symbol: '⚫', desc: 'All channels are identical.', rarity: 'Rare' },
    web_safe: { name: 'Web Safe', points: 50216, symbol: '🕸️', desc: 'A classic web-safe color.', rarity: 'Rare' },
    palindrome: { name: 'Hex Palindrome', points: 175571, symbol: '🪞', desc: 'Your hex reads the same backwards.', rarity: 'Epic' },
    f1: { name: 'F1', points: 75001, symbol: '🏎️', desc: 'Your hex contains F1.', rarity: 'Rare' },
    dead: { name: 'DEAD', points: 307005, symbol: '💀', desc: 'Your hex contains DEAD.', rarity: 'Epic' },
    beef: { name: 'BEEF', points: 298879, symbol: '🥩', desc: 'Your hex contains BEEF.', rarity: 'Epic' },
    cafe: { name: 'CAFE', points: 251966, symbol: '☕', desc: 'Your hex contains CAFE.', rarity: 'Epic' },
    face: { name: 'FACE', points: 264206, symbol: '😎', desc: 'Your hex contains FACE.', rarity: 'Epic' },
    fade: { name: 'FADE', points: 224222, symbol: '🕳️', desc: 'Your hex contains FADE.', rarity: 'Epic' },
    feed: { name: 'FEED', points: 265261, symbol: '🍼', desc: 'Your hex contains FEED.', rarity: 'Epic' },
    food: { name: 'F00D', points: 226453, symbol: '🍔', desc: 'Your hex contains F00D.', rarity: 'Epic' },
    leet: { name: '1337', points: 251337, symbol: '💻', desc: 'Your hex contains 1337.', rarity: 'Epic' },
    james_bond: { name: '007', points: 100007, symbol: '🕵️', desc: 'Your hex contains 007.', rarity: 'Rare' },
    blaze_it: { name: '420', points: 75420, symbol: '🌿', desc: 'Your hex contains 420.', rarity: 'Rare' },
    prime_sum: { name: 'Prime Energy', points: 15013, symbol: '🔢', desc: 'Your RGB sum is prime.', rarity: 'Uncommon' },
    fibonacci_sum: { name: 'Fibonacci Energy', points: 25021, symbol: '🌀', desc: 'Your RGB sum is a Fibonacci number.', rarity: 'Uncommon' },
    gentle_contrast: { name: 'Gentle Contrast', points: 3021, symbol: '🌫️', desc: 'A softly layered channel range.', rarity: 'Common' },
    layered_contrast: { name: 'Layered Contrast', points: 6080, symbol: '🪜', desc: 'A clearly layered channel range.', rarity: 'Common' },
    pastel: { name: 'Pastel Bloom', points: 25210, symbol: '🌸', desc: 'Bright channels with a soft range.', rarity: 'Uncommon' },
    neon: { name: 'Neon Voltage', points: 30220, symbol: '💡', desc: 'A vivid high-contrast color.', rarity: 'Uncommon' },
    luminous_core: { name: 'Luminous Core', points: 40090, symbol: '✨', desc: 'Bright, pale, and luminous.', rarity: 'Rare' },
    triple_crown: { name: 'Triple Crown', points: 175003, symbol: '👑', desc: 'One low, one middle, and one maximum channel.', rarity: 'Epic' },
    saturation_spike: { name: 'Saturation Spike', points: 20095, symbol: '🎨', desc: 'Extremely saturated color energy.', rarity: 'Uncommon' },
    vivid_saturation: { name: 'Vivid Saturation', points: 12070, symbol: '🟣', desc: 'Strong color saturation.', rarity: 'Common' },
    rich_saturation: { name: 'Rich Saturation', points: 7040, symbol: '🎨', desc: 'Balanced color saturation.', rarity: 'Common' },
    muted_saturation: { name: 'Muted Saturation', points: 3015, symbol: '🫧', desc: 'Subtle color saturation.', rarity: 'Common' },
    soft_saturation: { name: 'Soft Saturation', points: 1008, symbol: '☁️', desc: 'Near-neutral color saturation.', rarity: 'Common' },
    shadow_tone: { name: 'Shadow Tone', points: 15015, symbol: '🌑', desc: 'Very low lightness.', rarity: 'Uncommon' },
    deep_tone: { name: 'Deep Tone', points: 7035, symbol: '🌌', desc: 'Low lightness.', rarity: 'Common' },
    balanced_tone: { name: 'Balanced Tone', points: 3050, symbol: '⚖️', desc: 'Mid-range lightness.', rarity: 'Common' },
    bright_tone: { name: 'Bright Tone', points: 7065, symbol: '☀️', desc: 'High lightness.', rarity: 'Common' },
    luminous_tone: { name: 'Luminous Tone', points: 15085, symbol: '✨', desc: 'Very high lightness.', rarity: 'Uncommon' },
    red_dominant: { name: 'Red Dominant', points: 4777, symbol: '🔴', desc: 'Red leads the channel mix.', rarity: 'Common' },
    green_dominant: { name: 'Green Dominant', points: 4777, symbol: '🟢', desc: 'Green leads the channel mix.', rarity: 'Common' },
    blue_dominant: { name: 'Blue Dominant', points: 4777, symbol: '🔵', desc: 'Blue leads the channel mix.', rarity: 'Common' },
    balanced_channels: { name: 'Balanced Channels', points: 2888, symbol: '⚪', desc: 'No channel strongly dominates.', rarity: 'Common' },
    repeated_pair: { name: 'Repeated Pair', points: 150222, symbol: '🟰', desc: 'Your hex repeats the same byte three times.', rarity: 'Epic' },
    triple_hex: { name: 'Triple Hex', points: 90333, symbol: '3️⃣', desc: 'Three matching hexadecimal characters in a row.', rarity: 'Rare' },
    pure_black: { name: 'The Void', points: 1677721, symbol: '🌑', desc: 'Pure Black (#000000).', rarity: 'Mythic' },
    pure_white: { name: 'The Light', points: 1677721, symbol: '☀️', desc: 'Pure White (#FFFFFF).', rarity: 'Mythic' },
    pure_red: { name: 'Maximum Red', points: 750255, symbol: '🟥', desc: 'Pure Red (#FF0000).', rarity: 'Anomaly' },
    pure_green: { name: 'Maximum Green', points: 750255, symbol: '🟩', desc: 'Pure Green (#00FF00).', rarity: 'Anomaly' },
    pure_blue: { name: 'Maximum Blue', points: 750255, symbol: '🟦', desc: 'Pure Blue (#0000FF).', rarity: 'Anomaly' },
    pure_gold: { name: 'Midas', points: 1500079, symbol: '🥇', desc: 'Pure Gold (#FFD700).', rarity: 'Mythic' },
    streamer_purple: { name: 'Streamer Purple', points: 1014570, symbol: '🟣', desc: 'Brand Match (145,70,255).', rarity: 'Mythic' },
    audio_stream_green: { name: 'Audio Stream Green', points: 1030215, symbol: '🟢', desc: 'Brand Match (30,215,96).', rarity: 'Mythic' },
    classic_cola_red: { name: 'Classic Cola Red', points: 1024409, symbol: '🥤', desc: 'Brand Match (244,0,9).', rarity: 'Mythic' }
};

export function getBadgeMeta(id) {
    if (id.startsWith('ach_')) {
        const achievementId = id.replace('ach_', '');
        return CANDIDATE_ACHIEVEMENTS[achievementId] || ACHIEVEMENTS[achievementId] || { name: id, points: 0, symbol: '❓', desc: 'Unknown Achievement', rarity: 'Common' };
    }
    if (id.startsWith('hue_family_')) {
        const family = id.replace('hue_family_', '');
        return { name: `${family.charAt(0).toUpperCase()}${family.slice(1)} Hue`, points: 199, symbol: '🌈', desc: 'Your color belongs to this hue family.', rarity: 'Common' };
    }
    if (id === 'sum_even' || id === 'sum_odd') return { name: id === 'sum_even' ? 'Even Pulse' : 'Odd Pulse', points: id === 'sum_even' ? 401 : 403, symbol: '🔢', desc: 'The RGB channel sum has this parity.', rarity: 'Common' };
    if (id === 'even_channel_harmony' || id === 'odd_channel_rhythm' || id === 'mixed_channel_rhythm') return { name: id === 'even_channel_harmony' ? 'Even Channel Harmony' : id === 'odd_channel_rhythm' ? 'Odd Channel Rhythm' : 'Mixed Channel Rhythm', points: 101, symbol: '🎛️', desc: 'The channel values create this parity rhythm.', rarity: 'Common' };
    if (id === 'balanced_sum_band') return { name: 'Balanced Sum', points: 0, symbol: '⚖️', desc: 'The RGB sum sits in a balanced range.', rarity: 'Common' };
    if (id === 'vivid_contrast') return { name: 'Vivid Contrast', points: 10013, symbol: '🌈', desc: 'A vivid color with a broad channel span.', rarity: 'Uncommon' };
    if (id === 'edge_luminance') return { name: 'Edge Luminance', points: 7011, symbol: '☀️', desc: 'The color sits near a light or dark boundary.', rarity: 'Common' };
    if (id === 'channel_span') return { name: 'Wide Channel Span', points: 8008, symbol: '↔️', desc: 'The channels stretch across a wide range.', rarity: 'Common' };
    if (id === 'hex_letter_rich') return { name: 'Letter-Rich Hex', points: 2203, symbol: '🔤', desc: 'The hex code contains several A–F characters.', rarity: 'Common' };
    if (id === 'channel_edge') return { name: 'Edge Channel', points: 3503, symbol: '📐', desc: 'At least one channel approaches an RGB edge.', rarity: 'Common' };
    if (id === 'extreme_span') return { name: 'Extreme Span', points: 9009, symbol: '⚡', desc: 'The channel range is exceptionally wide.', rarity: 'Uncommon' };
    if (id === 'mirror_channels') return { name: 'Mirror Channels', points: 9009, symbol: '🪞', desc: 'Red and blue channels mirror each other.', rarity: 'Uncommon' };
    if (id === 'hex_echo') return { name: 'Hex Echo', points: 7007, symbol: '🔁', desc: 'The hex code repeats a neighboring character.', rarity: 'Common' };
    if (id.startsWith('temperature_')) {
        const temperature = id.replace('temperature_', '');
        return { name: `${temperature.charAt(0).toUpperCase()}${temperature.slice(1)} Temperature`, points: 197, symbol: '🌡️', desc: 'Your channels create this color temperature.', rarity: 'Common' };
    }
    if (id === 'condition_cascade') return { name: 'Condition Cascade', points: 20021, symbol: '⛓️', desc: 'A dense stack of scoring conditions aligned.', rarity: 'Rare' };
    if (id === 'condition_storm') return { name: 'Condition Storm', points: 210069, symbol: '🌪️', desc: 'An unusually dense condition stack.', rarity: 'Epic' };
    if (id === 'condition_supernova') return { name: 'Condition Supernova', points: 10000013, symbol: '💥', desc: 'An extraordinary convergence of conditions.', rarity: 'Mythic' };
    return CANDIDATE_BADGES[id] || BADGES[id] || { name: id, points: 0, symbol: '❓', desc: 'Unknown Badge', rarity: 'Common' };
}
