-- Canonical seed data for fresh Supabase resets.
--
-- This keeps a new database playable without any manual dashboard setup.

INSERT INTO public.achievements (id, name, description, icon, ep_reward, rarity) VALUES
('first_roll', 'First Steps', 'Roll the die for the first time.', '🎲', 5000, 'Common'),
('roll_10', 'Dedicated', 'Roll the die 10 times.', '🧡', 25000, 'Common'),
('roll_50', 'Veteran', 'Roll the die 50 times.', '💜', 100000, 'Rare'),
('roll_100', 'Centurion', 'Roll the die 100 times.', '💯', 250000, 'Epic'),
('roll_365', 'Annual', 'Roll the die 365 times.', '📅', 1000000, 'Mythic'),
('streak_7', 'Week Warrior', 'Maintain a 7-day streak.', '🔥', 50000, 'Common'),
('streak_14', 'Fortnight', 'Maintain a 14-day streak.', '🔥', 100000, 'Rare'),
('streak_30', 'Monthly Grinder', 'Maintain a 30-day streak.', '📅', 250000, 'Epic'),
('streak_100', 'Iron Will', 'Maintain a 100-day streak.', '🔥', 750000, 'Mythic'),
('rarity_rare', 'Uncommonly Rare', 'Roll a Rare color.', '🔵', 25000, 'Common'),
('rarity_epic', 'Epic Encounter', 'Roll an Epic rarity color.', '🟣', 100000, 'Rare'),
('rarity_anomaly', 'Anomaly Detected', 'Roll an Anomaly rarity color.', '🟠', 250000, 'Epic'),
('mythic_roll', 'Mythic Touch', 'Roll a Mythic rarity color.', '🌟', 500000, 'Mythic'),
('score_50k', 'High Roller', 'Score at least 50,000 EP in a single roll.', '💰', 25000, 'Common'),
('score_100k', 'Six Digits', 'Score at least 100,000 EP in a single roll.', '💰', 100000, 'Rare'),
('score_200k', 'Anomaly Hunter', 'Score at least 200,000 EP in a single roll.', '💰', 250000, 'Epic'),
('score_1_5m', 'Once in a Spectrum', 'Score at least 1,500,000 EP in a single roll.', '🌈', 500000, 'Mythic'),
('roll_prime', 'Prime Number', 'Roll a color with a prime R+G+B sum.', '🔢', 25000, 'Common'),
('high_contrast', 'Polarized Channels', 'Roll a color with an extreme RGB range.', '🌓', 25000, 'Common'),
('low_contrast', 'Close Harmony', 'Roll a color with very close RGB channels.', '🌫️', 15000, 'Common'),
('greyscale', 'Perfect Greyscale', 'Roll a pure greyscale color.', '⚫', 50000, 'Rare'),
('web_safe', 'Web Safe', 'Roll a classic web-safe color.', '🕸️', 50000, 'Rare'),
('roll_42_sum', 'Meaning of Life', 'Roll a color where R+G+B is exactly 42.', '🧬', 100000, 'Rare'),
('roll_beef', 'Where is the Beef?', 'Roll a hex containing BEEF.', '🥩', 100000, 'Rare'),
('roll_cafe', 'Coffee Break', 'Roll a hex containing CAFE.', '☕', 100000, 'Rare'),
('roll_dead', 'Dead Man Walking', 'Roll a hex containing DEAD.', '💀', 100000, 'Rare'),
('roll_face', 'Face Value', 'Roll a hex containing FACE.', '😎', 100000, 'Rare'),
('roll_palindrome', 'Mirror', 'Roll a hex palindrome.', '🪞', 150000, 'Epic'),
('repeated_pair', 'Repeated Pair', 'Roll a hex that repeats the same byte three times.', '🟰', 125000, 'Epic'),
('saturation_spike', 'Saturation Spike', 'Roll an extremely saturated color.', '🎨', 50000, 'Rare'),
('triple_crown', 'Triple Crown', 'Roll one low, one middle, and one maximum channel.', '👑', 150000, 'Epic'),
('pastel_soft', 'Pastel Bloom', 'Roll a bright, soft pastel color.', '🌸', 50000, 'Rare'),
('neon_bright', 'Neon Voltage', 'Roll a vivid high-contrast color.', '💡', 50000, 'Rare'),
('roll_black', 'The Void', 'Roll Pure Black (#000000).', '🌑', 500000, 'Mythic'),
('roll_white', 'The Light', 'Roll Pure White (#FFFFFF).', '☀️', 500000, 'Mythic'),
('roll_gold', 'Midas', 'Roll Pure Gold (#FFD700).', '🥇', 500000, 'Mythic'),
('pure_red', 'Maximum Red', 'Roll Pure Red (#FF0000).', '🟥', 250000, 'Epic'),
('pure_green', 'Maximum Green', 'Roll Pure Green (#00FF00).', '🟩', 250000, 'Epic'),
('pure_blue', 'Maximum Blue', 'Roll Pure Blue (#0000FF).', '🟦', 250000, 'Epic'),
('streamer_purple', 'Streamer Purple', 'Roll Streamer Purple.', '🟣', 350000, 'Mythic'),
('audio_stream_green', 'Audio Stream Green', 'Roll Audio Stream Green.', '🟢', 350000, 'Mythic'),
('classic_cola_red', 'Classic Cola Red', 'Roll Classic Cola Red.', '🥤', 350000, 'Mythic')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.shop_items (item_key, name, slot, cost, css_type, css_value, available_from, available_until, rarity, description, collection) VALUES
('border_celestial', 'Celestial Border', 'profile_border', 600000, 'renderer', 'celestial', NULL, NULL, 'Mythic', 'A precise celestial edge with a restrained star-like pulse.', 'Prism'),
('border_chroma', 'Chroma Border', 'profile_border', 450000, 'renderer', 'chroma', NULL, NULL, 'Mythic', 'A spectrum edge that moves through the profile without overwhelming it.', 'Prism'),
('border_crystal', 'Crystal Border', 'profile_border', 450000, 'renderer', 'crystal', NULL, NULL, 'Mythic', 'A cool faceted edge with a clean crystalline glint.', 'Prism'),
('border_glitch', 'Glitch Border', 'profile_border', 500000, 'renderer', 'glitch', NULL, NULL, 'Mythic', 'A clipped signal edge with brief cyan and rose interruptions.', 'Static Bloom'),
('border_gold', 'Gold Border', 'profile_border', 350000, 'renderer', 'gold', NULL, NULL, 'Mythic', 'A warm archival metal edge with a measured glint.', 'Archive'),
('border_neon', 'Neon Border', 'profile_border', 180000, 'renderer', 'neon', NULL, NULL, 'Epic', 'A clean electric edge that breathes between cyan and mint.', 'Signal'),
('border_prism', 'Prism Border', 'profile_border', 300000, 'renderer', 'prism', NULL, NULL, 'Epic', 'Refracted light travels around the profile edge in a compact spectrum.', 'Prism'),
('border_void', 'Void Border', 'profile_border', 550000, 'renderer', 'void', NULL, NULL, 'Mythic', 'A dark violet edge that absorbs light around the card.', 'Nocturne'),
('border_signal', 'Signal Border', 'profile_border', 160000, 'renderer', 'signal', NULL, NULL, 'Rare', 'A quiet lime edge with a bounded signal pulse.', 'Signal'),
('streak_freeze', 'Streak Freeze', 'consumable', 50000, 'text', 'Protects your streak if you miss a day.', NULL, NULL, 'Rare', 'Protects your streak if you miss a day.', NULL),
('title_founder', 'Founder Title', 'title', 0, 'text', '✦ FOUNDER ✦', NULL, '2026-07-10', 'Mythic', 'Reserved for people whose early contributions helped shape ChromaDie.', 'Project Legacy')
ON CONFLICT (item_key) DO NOTHING;

INSERT INTO public.shop_items (
  item_key, name, slot, cost, css_type, css_value, available_from, available_until,
  rarity, description, collection, stackable, access_tier, entitlement_key, catalog_status
) VALUES
  ('name_font_editorial_serif', 'Velvet Antiqua', 'name_font', 180000, 'renderer', 'editorial-serif', NULL, NULL, 'Rare', 'A measured serif with high-contrast strokes for an archival signature.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_font_condensed_sans', 'Narrowcast', 'name_font', 180000, 'renderer', 'condensed-sans', NULL, NULL, 'Rare', 'A narrow sans-serif that gives the name a compact editorial profile.', 'Nocturne', false, 'earned', NULL, 'active'),
  ('name_font_wide_geometric', 'Monument', 'name_font', 180000, 'renderer', 'wide-geometric', NULL, NULL, 'Rare', 'A broad geometric display face with open, architectural forms.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_font_mono_compact', 'Fixed Point', 'name_font', 120000, 'renderer', 'mono-compact', NULL, NULL, 'Uncommon', 'A precise bundled monospace with compact technical rhythm.', 'Signal', false, 'earned', NULL, 'active'),
  ('name_font_rounded_mono', 'Soft Circuit', 'name_font', 170000, 'renderer', 'rounded-mono', NULL, NULL, 'Rare', 'A softened monospace with rounded terminals and steady spacing.', 'Static Bloom', false, 'earned', NULL, 'active'),
  ('name_font_soft_grotesk', 'Lowlight', 'name_font', 130000, 'renderer', 'soft-grotesk', NULL, NULL, 'Uncommon', 'A calm modern sans with balanced proportions for everyday identity.', 'Nocturne', false, 'earned', NULL, 'active'),
  ('name_font_humanist_display', 'Paper Lantern', 'name_font', 190000, 'renderer', 'humanist-display', NULL, NULL, 'Rare', 'A warm humanist display face with readable, lifted curves.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_font_modern_fraktur', 'Black Cathedral', 'name_font', 320000, 'renderer', 'modern-fraktur', NULL, NULL, 'Epic', 'A dramatic blackletter-inspired face with carved historical character.', 'Nocturne', false, 'earned', NULL, 'active'),
  ('name_font_pixel_display', 'Raster Bloom', 'name_font', 190000, 'renderer', 'pixel-display', NULL, NULL, 'Rare', 'A squared display face that gives the name a deliberate digital edge.', 'Static Bloom', false, 'earned', NULL, 'active'),
  ('name_font_high_contrast_italic', 'Razor Script', 'name_font', 310000, 'renderer', 'high-contrast-italic', NULL, NULL, 'Epic', 'A sharp italic display face with a fashion-editorial slant.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_font_neo_slab', 'Foundry Slab', 'name_font', 210000, 'renderer', 'neo-slab', NULL, NULL, 'Rare', 'A sturdy slab serif that gives the name a printed, grounded weight.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_font_reverse_contrast', 'Split Serif', 'name_font', 330000, 'renderer', 'reverse-contrast', NULL, NULL, 'Epic', 'A sculptural display face with unexpected thick-and-thin contrast.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_font_industrial_stencil', 'Cutline', 'name_font', 340000, 'renderer', 'industrial-stencil', NULL, NULL, 'Epic', 'A cut stencil face with utilitarian, engineered lettering.', 'Signal', false, 'earned', NULL, 'active'),
  ('name_font_futurist_extended', 'Longwave', 'name_font', 230000, 'renderer', 'futurist-extended', NULL, NULL, 'Rare', 'An extended geometric face that stretches the name into a horizon.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_font_terminal_bitmap', 'Greenroom', 'name_font', 190000, 'renderer', 'terminal-bitmap', NULL, NULL, 'Rare', 'A low-resolution terminal face with unmistakable screen-era texture.', 'Static Bloom', false, 'earned', NULL, 'active'),
  ('name_font_rounded_display', 'Soft Orbit', 'name_font', 210000, 'renderer', 'rounded-display', NULL, NULL, 'Rare', 'A friendly rounded display face with soft, confident volume.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_font_marker_tag', 'Handstamp', 'name_font', 350000, 'renderer', 'marker-tag', NULL, NULL, 'Epic', 'A hand-marked face that gives the name a quick, personal gesture.', 'Ember', false, 'earned', NULL, 'active'),
  ('name_font_newspaper_black', 'Front Page', 'name_font', 320000, 'renderer', 'newspaper-black', NULL, NULL, 'Epic', 'A dense headline face with the authority of a printed front page.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_material_polished_chrome', 'Cold Mirror', 'name_material', 340000, 'renderer', 'polished-chrome', NULL, NULL, 'Epic', 'A cool reflective metal finish with crisp silver highlights across the letters.', 'Nocturne', false, 'earned', NULL, 'active'),
  ('name_material_copper_press', 'Oxide Press', 'name_material', 220000, 'renderer', 'copper-press', NULL, NULL, 'Rare', 'A warm pressed-copper surface with dark edges and burnished light.', 'Ember', false, 'earned', NULL, 'active'),
  ('name_material_glass_emboss', 'Raised Glass', 'name_material', 350000, 'renderer', 'glass-emboss', NULL, NULL, 'Epic', 'A translucent embossed surface with a raised, refracted edge.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_material_fine_outline', 'Hairline', 'name_material', 140000, 'renderer', 'fine-outline', NULL, NULL, 'Uncommon', 'A precise hairline contour that lets the daily color breathe through.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_material_ink_bleed', 'Wet Type', 'name_material', 210000, 'renderer', 'ink-bleed', NULL, NULL, 'Rare', 'A soft paper-and-ink edge that blooms gently beyond the glyphs.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_material_pearl_foil', 'Mother of Pearl', 'name_material', 360000, 'renderer', 'pearl-foil', NULL, NULL, 'Epic', 'A pearlescent foil with quiet pastel reflections and a polished face.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_material_carbon_cut', 'Carbon Vein', 'name_material', 230000, 'renderer', 'carbon-cut', NULL, NULL, 'Rare', 'A dark carbon surface scored with restrained silver facets.', 'Nocturne', false, 'earned', NULL, 'active'),
  ('name_material_frosted_edge', 'Ice Line', 'name_material', 210000, 'renderer', 'frosted-edge', NULL, NULL, 'Rare', 'An icy face with a clean frosted rim and high readability.', 'Signal', false, 'earned', NULL, 'active'),
  ('name_material_holographic_film', 'Spectral Film', 'name_material', 540000, 'renderer', 'holographic-film', NULL, NULL, 'Anomaly', 'A thin holographic film that shifts through restrained spectral bands.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_material_cut_paper', 'Scissorwork', 'name_material', 200000, 'renderer', 'cut-paper', NULL, NULL, 'Rare', 'Layered paper edges give the name a tactile handmade profile.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_material_neon_tube', 'Afterglow', 'name_material', 380000, 'renderer', 'neon-tube', NULL, NULL, 'Epic', 'A bounded neon-tube face with a bright inner core and colored rim.', 'Signal', false, 'earned', NULL, 'active'),
  ('name_material_liquid_mercury', 'Quicksilver', 'name_material', 560000, 'renderer', 'liquid-mercury', NULL, NULL, 'Anomaly', 'A fluid mercury surface with bright specular bands and dark weight.', 'Nocturne', false, 'earned', NULL, 'active'),
  ('name_material_oil_slick', 'Spillway', 'name_material', 390000, 'renderer', 'oil-slick', NULL, NULL, 'Epic', 'An oil-slick surface blends deep violet, teal, and amber reflections.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_material_thermal_ink', 'Heat Map', 'name_material', 380000, 'renderer', 'thermal-ink', NULL, NULL, 'Epic', 'Heat-responsive ink shifts from cool violet through cyan, gold, and rose.', 'Signal', false, 'earned', NULL, 'active'),
  ('name_material_velvet_ink', 'Soft Black', 'name_material', 250000, 'renderer', 'velvet-ink', NULL, NULL, 'Rare', 'A plush velvet surface with a saturated pile and soft highlight.', 'Ember', false, 'earned', NULL, 'active'),
  ('name_material_embroidered_thread', 'Threadwork', 'name_material', 370000, 'renderer', 'embroidered-thread', NULL, NULL, 'Epic', 'Thread-like ridges give the letters a tactile stitched surface.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_material_engraved_stone', 'Quarry Mark', 'name_material', 260000, 'renderer', 'engraved-stone', NULL, NULL, 'Rare', 'A carved stone face with durable shadowed grooves and pale edges.', 'Nocturne', false, 'earned', NULL, 'active'),
  ('name_material_crt_phosphor', 'Cathode Bloom', 'name_material', 350000, 'renderer', 'crt-phosphor', NULL, NULL, 'Epic', 'A green phosphor face with a controlled screen glow and scan texture.', 'Static Bloom', false, 'earned', NULL, 'active'),
  ('name_material_gold_leaf', 'Gilded', 'name_material', 570000, 'renderer', 'gold-leaf', NULL, NULL, 'Anomaly', 'Layered gold leaf catches warm highlights across the letterforms.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_material_chroma_glass', 'Color Prism', 'name_material', 400000, 'renderer', 'chroma-glass', NULL, NULL, 'Epic', 'A translucent glass face carries a bounded spectrum around the daily color.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_material_ceramic_glaze', 'Kiln Glow', 'name_material', 390000, 'renderer', 'ceramic-glaze', NULL, NULL, 'Epic', 'A fired ceramic glaze adds a smooth warm coat and deep edge.', 'Ember', false, 'earned', NULL, 'active'),
  ('name_material_blueprint_ink', 'Draftline', 'name_material', 240000, 'renderer', 'blueprint-ink', NULL, NULL, 'Rare', 'A technical blue ink face with pale drafting-line highlights.', 'Signal', false, 'earned', NULL, 'active'),
  ('name_motion_velvet_sweep', 'Satin Pass', 'name_motion', 360000, 'renderer', 'velvet-sweep', NULL, NULL, 'Epic', 'A soft satin highlight travels across the name.', 'Ember', false, 'earned', NULL, 'active'),
  ('name_motion_refraction_sweep', 'Split Light', 'name_motion', 350000, 'renderer', 'refraction-sweep', NULL, NULL, 'Epic', 'Cyan and rose refraction bands cross the letters.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_motion_ghost_offset', 'Double Exposure', 'name_motion', 320000, 'renderer', 'ghost-offset', NULL, NULL, 'Epic', 'Slow chromatic echoes drift behind the name.', 'Static Bloom', false, 'earned', NULL, 'active'),
  ('name_motion_focus_resolve', 'Come Into Focus', 'name_motion', 230000, 'renderer', 'focus-resolve', NULL, NULL, 'Rare', 'The name resolves from controlled blur.', 'Nocturne', false, 'earned', NULL, 'active'),
  ('name_motion_mask_reveal', 'Curtain Lift', 'name_motion', 210000, 'renderer', 'mask-reveal', NULL, NULL, 'Rare', 'A clean horizontal reveal.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_motion_quiet_afterimage', 'Residual', 'name_motion', 240000, 'renderer', 'quiet-afterimage', NULL, NULL, 'Rare', 'A restrained delayed copy trails the text.', 'Static Bloom', false, 'earned', NULL, 'active'),
  ('name_motion_soft_rise', 'Lift Off', 'name_motion', 150000, 'renderer', 'soft-rise', NULL, NULL, 'Uncommon', 'A subtle entrance from below.', 'Ember', false, 'earned', NULL, 'active'),
  ('name_motion_scanline_reveal', 'Scan In', 'name_motion', 330000, 'renderer', 'scanline-reveal', NULL, NULL, 'Epic', 'A scanning line reveals the name.', 'Signal', false, 'earned', NULL, 'active'),
  ('name_motion_particle_drift', 'Dustfall', 'name_motion', 370000, 'renderer', 'particle-drift', NULL, NULL, 'Epic', 'Small particles lift from the letterforms.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_motion_letter_shuffle', 'Scramble', 'name_motion', 520000, 'renderer', 'letter-shuffle', NULL, NULL, 'Anomaly', 'Characters rearrange before locking into place.', 'Static Bloom', false, 'earned', NULL, 'active'),
  ('name_motion_fuzzy_signal', 'Ghost Frequency', 'name_motion', 340000, 'renderer', 'fuzzy-signal', NULL, NULL, 'Epic', 'Controlled horizontal signal slices distort the name.', 'Signal', false, 'earned', NULL, 'active'),
  ('name_motion_typewriter_name', 'Keyed In', 'name_motion', 230000, 'renderer', 'typewriter-name', NULL, NULL, 'Rare', 'Characters appear one by one.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_motion_chromatic_ripple', 'Color Wake', 'name_motion', 410000, 'renderer', 'chromatic-ripple', NULL, NULL, 'Epic', 'A colored wave bends vertical sections of the letters.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_motion_liquid_fill', 'Floodline', 'name_motion', 580000, 'renderer', 'liquid-fill', NULL, NULL, 'Anomaly', 'Today’s color rises inside the name and settles.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_motion_pixel_dissolve', 'Rasterfall', 'name_motion', 390000, 'renderer', 'pixel-dissolve', NULL, NULL, 'Epic', 'The name assembles from a field of square fragments.', 'Static Bloom', false, 'earned', NULL, 'active'),
  ('name_motion_echo_collapse', 'Convergence', 'name_motion', 380000, 'renderer', 'echo-collapse', NULL, NULL, 'Epic', 'Distant copies converge into the final name.', 'Nocturne', false, 'earned', NULL, 'active'),
  ('name_motion_heat_shimmer', 'Mirage', 'name_motion', 270000, 'renderer', 'heat-shimmer', NULL, NULL, 'Rare', 'Thin horizontal bands refract like rising heat.', 'Ember', false, 'earned', NULL, 'active'),
  ('name_motion_signal_lock', 'Lockstep', 'name_motion', 370000, 'renderer', 'signal-lock', NULL, NULL, 'Epic', 'Misaligned signal slices snap cleanly into place.', 'Signal', false, 'earned', NULL, 'active'),
  ('name_motion_letter_cascade', 'Typefall', 'name_motion', 380000, 'renderer', 'letter-cascade', NULL, NULL, 'Epic', 'Characters fall individually into their final positions.', 'Archive', false, 'earned', NULL, 'active'),
  ('name_motion_orbiting_spark', 'Perihelion', 'name_motion', 400000, 'renderer', 'orbiting-spark', NULL, NULL, 'Epic', 'A bright spark traces around the name.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_motion_color_memory', 'Archive Loop', 'name_motion', 600000, 'renderer', 'color-memory', NULL, NULL, 'Anomaly', 'Recent rolled colors pass through the lettering in sequence.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_motion_daily_pulse', 'Solar Return', 'name_motion', 410000, 'renderer', 'daily-pulse', NULL, NULL, 'Epic', 'Today’s color blooms outward from the center.', 'Ember', false, 'earned', NULL, 'active'),
  ('name_motion_prism_shatter', 'Facet Break', 'name_motion', 760000, 'renderer', 'prism-shatter', NULL, NULL, 'Mythic', 'Faceted fragments separate and reassemble.', 'Prism', false, 'earned', NULL, 'active'),
  ('name_motion_ink_spread', 'Bloomline', 'name_motion', 390000, 'renderer', 'ink-spread', NULL, NULL, 'Epic', 'Soft ink expands into crisp finished letterforms.', 'Archive', false, 'earned', NULL, 'active')
ON CONFLICT (item_key) DO UPDATE SET
  name = EXCLUDED.name,
  slot = EXCLUDED.slot,
  cost = EXCLUDED.cost,
  css_type = EXCLUDED.css_type,
  css_value = EXCLUDED.css_value,
  rarity = EXCLUDED.rarity,
  description = EXCLUDED.description,
  collection = EXCLUDED.collection,
  stackable = EXCLUDED.stackable,
  access_tier = EXCLUDED.access_tier,
  entitlement_key = EXCLUDED.entitlement_key,
  catalog_status = EXCLUDED.catalog_status;

INSERT INTO public.meta (key, value) VALUES
('shop_version', '2026-08-02T20:00:00Z'),
('cotw_target', '73,114,201'),
('official_launch_at', '2026-07-11T00:00:00Z'),
('founder_window_ends_at', '2026-08-11T00:00:00Z')
ON CONFLICT (key) DO NOTHING;
