import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const read = path => readFile(new URL(`../${path}`, import.meta.url), 'utf8');
const home = await read('src/lib/HomePage.svelte');
const directory = await read('src/lib/HomepageProfileDirectory.svelte');
const preview = await read('src/lib/HomepageProfilePreview.svelte');
const ticker = await read('src/lib/HomepageLiveTicker.svelte');
const rollSummary = await read('src/lib/HomepageRollSummary.svelte');
const directoryData = await read('src/lib/homepageDirectory.js');
const audioControls = await read('src/lib/ProfileAudioControls.svelte');
const profileMusic = await read('src/lib/ProfileMusic.svelte');
const app = await read('src/App.svelte');
const routeLoaders = await read('src/lib/routeLoaders.js');
const main = await read('src/main.js');
const guestProfile = await read('src/lib/GuestProfileOnboarding.svelte');

test('the homepage explains the daily identity loop with a direct claim action', () => {
  assert.match(home, /Public profiles\. One color roll a day/);
  assert.match(home, /Add your background, avatar, music, links, projects/);
  assert.match(home, /daily roll affects your leaderboard position/);
  assert.match(home, /Higher ranks make your profile easier to find/);
  assert.match(home, /Claim your username/);
  assert.match(home, /dispatch\('claim'/);
  assert.match(home, /chm\.lol\//);
  assert.match(home, /View your profile/);
  assert.match(home, /Claim your profile/);
  assert.match(home, /focusClaim/);
  assert.match(home, /width: min\(100%, 30rem\)/);
  assert.match(home, /\.home-page__claim-field input \{\s*flex: 1;/s);
  assert.match(home, /HomepageProfileDirectory/);
  assert.doesNotMatch(home, /HomeExampleProfiles|HomeRollShowcase|Mara|Mira|Nocturne|Solstice/);
  assert.match(home, /prefers-reduced-motion/);
  assert.match(main, /@fontsource-variable\/instrument-sans/);
  assert.match(main, /@fontsource-variable\/spline-sans/);
  assert.match(main, /@fontsource\/ibm-plex-mono/);
  assert.match(directory, /get_public_discovery/);
  assert.match(directory, /loadProfileContext/);
  assert.match(directory, /HomepageLiveTicker/);
  assert.match(directory, /HomepageProfilePreview/);
  assert.match(directory, /Explore all profiles/);
  assert.match(directory, /View today’s leaderboard/);
  assert.match(directory, /Roll once a day\. Your score changes your position/);
  assert.match(preview, /IdentityCard/);
  assert.match(preview, /ProfileAtmosphere/);
  assert.match(preview, /CompactRollPreview/);
  assert.match(preview, /ProfileMusic/);
  assert.match(preview, /getVisibleProfileLinks/);
  assert.match(preview, /No bio added yet/);
  assert.doesNotMatch(preview, /Mara|Mira|Nocturne|Solstice|example\.com/);
  assert.match(ticker, /Waiting for today’s public rolls/);
  assert.match(ticker, /prefers-reduced-motion/);
  assert.match(ticker, /focus-within/);
  assert.match(rollSummary, /getLatestHomepageRoll/);
  assert.match(directoryData, /KNOWN_STAFF_SHOWCASE_USERNAMES/);
  assert.match(audioControls, /profile-audio-control__toggle/);
  assert.match(audioControls, /profile-audio-control__volume/);
  assert.match(audioControls, /Play profile audio/);
  assert.match(profileMusic, /ProfileAudioControls/);
  assert.match(profileMusic, /deferMedia/);
});

test('the application mounts the homepage, signup flow, and global footer', () => {
  assert.match(app, /import HomePage from '.\/lib\/HomePage\.svelte'/);
  assert.match(app, /currentView === 'home'/);
  assert.match(app, /staticComponent: HomePage/);
  assert.match(app, /on:signup=\{\(\) => openAuthModal\('signup'\)\}/);
  assert.match(app, /<RouteOutlet/);
  assert.doesNotMatch(app, /<ProfileAtmosphere/);
  assert.match(app, /class:app-shell--home=\{homeModeVisible\}/);
  assert.match(app, /<footer class="site-footer">/);
  assert.match(app, /Privacy Policy/);
  assert.match(app, /How to Play/);
});

test('the signed-out profile route opens the guest onboarding roll', () => {
  assert.match(routeLoaders, /guestProfile: \(\) => import\('\.\/GuestProfileOnboarding\.svelte'\)/);
  assert.match(app, /loaderKey: 'guestProfile'/);
  assert.match(app, /componentProps: \{ guestActive \}/);
  assert.match(guestProfile, /This could be your profile/);
  assert.match(guestProfile, /See today’s roll/);
  assert.match(guestProfile, /guest-onboarding/);
  assert.match(guestProfile, /IdentityCard/);
  assert.match(guestProfile, /ProfileRoll/);
  assert.match(guestProfile, /Create your profile/);
});
