import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const home = await readFile(new URL('../src/lib/HomePage.svelte', import.meta.url), 'utf8');
const showcase = await readFile(new URL('../src/lib/HomeRollShowcase.svelte', import.meta.url), 'utf8');
const demoRoll = await readFile(new URL('../src/lib/HomeDemoRoll.svelte', import.meta.url), 'utf8');
const discovery = await readFile(new URL('../src/lib/HomeDiscovery.svelte', import.meta.url), 'utf8');
const guestRollFixture = await readFile(new URL('../src/lib/guestRollFixture.js', import.meta.url), 'utf8');
const profileRoll = await readFile(new URL('../src/lib/ProfileRoll.svelte', import.meta.url), 'utf8');
const app = await readFile(new URL('../src/App.svelte', import.meta.url), 'utf8');
const routeLoaders = await readFile(new URL('../src/lib/routeLoaders.js', import.meta.url), 'utf8');
const main = await readFile(new URL('../src/main.js', import.meta.url), 'utf8');
const guestProfile = await readFile(new URL('../src/lib/GuestProfileOnboarding.svelte', import.meta.url), 'utf8');

test('the homepage explains the daily identity loop with a direct claim action', () => {
  assert.match(home, /A public profile built through one daily color roll/);
  assert.match(home, /Roll once a day to collect colors, earn EP, unlock cosmetics/);
  assert.match(home, /Claim your username/);
  assert.match(home, /dispatch\('claim'/);
  assert.match(home, /chm\.lol\//);
  assert.match(home, /View your profile/);
  assert.doesNotMatch(home, /home-page__loop/);
  assert.doesNotMatch(home, /HomepageLiveProfiles/);
  assert.match(home, /prefers-reduced-motion/);
  assert.match(home, /HomeRollShowcase/);
  assert.match(main, /@fontsource-variable\/spline-sans/);
  assert.match(main, /@fontsource\/ibm-plex-mono/);
  assert.match(showcase, /import IdentityCard from '.\/IdentityCard\.svelte'/);
  assert.match(showcase, /import CompactRollPreview from '.\/CompactRollPreview\.svelte'/);
  assert.match(showcase, /import ProfileAtmosphere from '.\/ProfileAtmosphere\.svelte'/);
  assert.match(showcase, /profile_bg: 'bg_deep_space'/);
  assert.match(showcase, /profile_atmosphere: 'bg_rain'/);
  assert.match(showcase, /profile_border: 'border_chroma'/);
  assert.match(showcase, /avatarSrc="\/avatars\/mara-dog-v1\.jpg"/);
  assert.match(showcase, /<IdentityCard/);
  assert.match(showcase, /showToday=\{false\}/);
  assert.match(showcase, /Mara's color log/);
  assert.match(showcase, /Collecting bright colors, one day at a time/);
  assert.match(showcase, /Recent colors/);
  assert.match(showcase, /Roll once\. Improve your position/);
  assert.match(showcase, /Higher-scoring rolls earn more EP/);
  assert.match(showcase, /Get discovered/);
  assert.match(showcase, /Leaderboard/);
  assert.match(showcase, /--home-profile-accent/);
  assert.match(showcase, /18 colors collected · next roll in 08:42:16/);
  assert.match(showcase, /home-showcase__roll-result/);
  assert.match(showcase, /orb_shape: 'orb_hexagon'/);
  assert.match(showcase, /roll_effect: 'roll_sparkles'/);
  assert.match(showcase, /import HomeDemoRoll from '.\/HomeDemoRoll\.svelte'/);
  assert.match(showcase, /Try a sample roll/);
  assert.match(home, /import HomeDiscovery from '.\/HomeDiscovery\.svelte'/);
  assert.match(home, /<HomeDiscovery on:navigate={forwardAction}/);
  assert.match(demoRoll, /visualFixture="guest-onboarding"/);
  assert.match(demoRoll, /fixtureResult={guestRollFixture}/);
  assert.doesNotMatch(demoRoll, /requestRoll|supabase\.rpc/);
  assert.match(discovery, /get_public_discovery/);
  assert.match(discovery, /normalizeDiscoveryResponse/);
  assert.match(discovery, /p_limit: DISCOVERY_LIMIT/);
  assert.match(discovery, /No public profiles have entered today/);
  assert.match(guestRollFixture, /hex: '#B666C9'/);
  assert.match(profileRoll, /fixtureRollReady = visualFixture === 'guest-onboarding'/);
  assert.match(profileRoll, /authInitialized: \$authInitialized \|\| fixtureRollReady/);
  assert.doesNotMatch(showcase, /border-prism-anim|frame-diamond-anim|name-spectrum-anim|roll-sparkles-anim|orb-shape-diamond/);
});

test('the application mounts the homepage, signup flow, and global footer', () => {
  assert.match(app, /import HomePage from '.\/lib\/HomePage\.svelte'/);
  assert.match(app, /currentView === 'home'/);
  assert.match(app, /staticComponent: HomePage/);
  assert.match(app, /on:signup=\{\(\) => openAuthModal\('signup'\)\}/);
  assert.match(app, /<RouteOutlet/);
  assert.doesNotMatch(app, /<ProfileAtmosphere/);
  assert.match(app, /class:app-shell--home=\{homeModeVisible\}/);
  assert.match(app, /<footer class="site-footer">/);
  assert.match(app, /\.site-footer \{\s*position: relative;\s*z-index: 1;/s);
  assert.match(app, /Privacy Policy/);
  assert.match(app, /How to Play/);
});

test('the signed-out profile route opens the guest onboarding roll', () => {
  assert.match(routeLoaders, /guestProfile: \(\) => import\('\.\/GuestProfileOnboarding\.svelte'\)/);
  assert.match(app, /loaderKey: 'guestProfile'/);
  assert.match(app, /componentProps: \{ guestActive \}/);
  assert.match(guestProfile, /This could be your profile/);
  assert.match(guestProfile, /See today’s roll/);
  assert.match(guestProfile, /guest-onboarding/);
  assert.match(guestProfile, /IdentityCard/);
  assert.match(guestProfile, /ProfileRoll/);
  assert.match(guestProfile, /Create your profile/);
});
