INSERT INTO public.shop_items (item_key, name, slot, cost, css_type, css_value, rarity, description, collection) VALUES
('frame_30_day', 'Monthly Grinder Frame', 'frame', 0, 'class', 'frame-streak-30', 'Mythic', 'Unlocked at a 30-day streak. A breathing emerald milestone frame.', NULL),
('frame_100_day', 'Iron Will Frame', 'frame', 0, 'class', 'frame-streak-100', 'Mythic', 'Unlocked at a 100-day streak. A bright gold frame with a constant shine.', NULL),
('frame_365_day', 'Annual Frame', 'frame', 0, 'class', 'frame-streak-365', 'Mythic', 'Unlocked at a 365-day streak. A prismatic anniversary frame with a full aura.', NULL),
('frame_thin_white', 'Hairline Frame', 'frame', 40000, 'style', 'border: 1px solid rgba(255,255,255,0.35);', 'Uncommon', 'A thin white frame for a clean, minimal profile header.', NULL),
('frame_neon_pink', 'Pink Frame', 'frame', 150000, 'style', 'border: 1px solid #ff4fd8; box-shadow: 0 0 12px rgba(255,79,216,0.5);', 'Rare', 'A hot pink frame with a neon edge light.', NULL),
('frame_neon_cyan', 'Cyan Frame', 'frame', 150000, 'style', 'border: 1px solid #22d3ee; box-shadow: 0 0 12px rgba(34,211,238,0.5);', 'Rare', 'A bright cyan frame with a soft electric glow.', NULL),
('frame_corner', 'Corner Accents', 'frame', 250000, 'class', 'frame-corner-accents', 'Rare', 'Four luminous corner brackets around your name frame.', 'Geometric'),
('frame_gold_ring', 'Gold Ring', 'frame', 600000, 'style', 'border: 1px solid #f1c40f; box-shadow: 0 0 16px rgba(241,196,15,0.45);', 'Epic', 'A slim gold frame with a warm halo.', 'Royal Metals'),
('frame_double', 'Holo Frame', 'frame', 1000000, 'class', 'frame_holo', 'Epic', 'An iridescent cyan-magenta frame with a moving holo sweep.', 'Geometric'),
('frame_chroma', 'Chroma Frame', 'frame', 4000000, 'class', 'frame-chroma-anim', 'Epic', 'A saturated spectrum edge racing around a dark core.', 'Chroma'),
('frame_platinum', 'Platinum Frame', 'frame', 5000000, 'class', 'frame-platinum-shine', 'Mythic', 'A polished silver frame with a cold metallic shimmer.', 'Royal Metals'),
('frame_diamond', 'Diamond Frame', 'frame', 10000000, 'class', 'frame-diamond-anim', 'Mythic', 'An icy crystal frame with a fast white-blue shimmer.', 'Royal Metals'),
('name_italic', 'Italic Font', 'name_effect', 50000, 'style', 'font-style: italic; color: #fff;', 'Uncommon', 'An italic username with a sharp, clean slant.', NULL),
('name_drop_shadow', 'Drop Shadow', 'name_effect', 50000, 'class', 'name_drop_shadow', 'Uncommon', 'A white name with a deep shadow for stronger contrast.', NULL),
('name_smallcaps', 'Small Caps', 'name_effect', 75000, 'style', 'font-variant: small-caps; color: #fff; letter-spacing: 1px;', 'Uncommon', 'A small-caps username with a refined look.', NULL),
('name_glow_green', 'Green Glow', 'name_effect', 100000, 'style', 'text-shadow: 0 0 10px #2ecc71; color: #fff;', 'Rare', 'Green glow text with a vivid neon edge.', NULL),
('name_glow_red', 'Red Glow', 'name_effect', 100000, 'style', 'text-shadow: 0 0 10px #ff4c4c; color: #fff;', 'Rare', 'Red glow text with a hot, alert-style edge.', NULL),
('name_glow_purple', 'Purple Glow', 'name_effect', 100000, 'style', 'text-shadow: 0 0 10px #9b59b6; color: #fff;', 'Rare', 'Purple glow text with a softer magenta tint.', NULL),
('name_glow_blue', 'Blue Glow', 'name_effect', 100000, 'style', 'text-shadow: 0 0 10px #3498db; color: #fff;', 'Rare', 'Blue glow text that reads clearly on dark surfaces.', NULL),
('name_glow_pink_neon', 'Neon Pink Glow', 'name_effect', 250000, 'style', 'text-shadow: 0 0 5px #ff00de, 0 0 10px #ff00de; color: #fff;', 'Rare', 'A bright neon pink text glow.', NULL),
('name_glow_gold', 'Gold Glow', 'name_effect', 500000, 'style', 'text-shadow: 0 0 15px #f1c40f; color: #fff;', 'Epic', 'A gold glow effect with a premium shine.', NULL),
('name_gradient_purple', 'Purple Gradient', 'name_effect', 500000, 'style', 'background: linear-gradient(45deg, #8E2DE2, #4A00E0); -webkit-background-clip: text; background-clip: text; color: transparent;', 'Epic', 'A purple gradient that clips directly to your name.', NULL),
('name_ice', 'Ice Gradient', 'name_effect', 750000, 'style', 'background: linear-gradient(45deg, #a1c4fd, #c2e9fb); -webkit-background-clip: text; background-clip: text; color: transparent;', 'Epic', 'A pale blue gradient with a cold glassy finish.', 'Elemental'),
('name_toxic', 'Toxic Gradient', 'name_effect', 750000, 'style', 'background: linear-gradient(45deg, #43e97b, #38f9d7); -webkit-background-clip: text; background-clip: text; color: transparent;', 'Epic', 'A bright acid-green gradient with a chemical glow.', 'Elemental'),
('name_gradient_fire', 'Fire Gradient', 'name_effect', 750000, 'style', 'background: linear-gradient(45deg, #f12711, #f5af19); -webkit-background-clip: text; background-clip: text; color: transparent;', 'Epic', 'A warm fire gradient for a hotter username look.', NULL),
('name_slow_pulse', 'Slow Pulse', 'name_effect', 1000000, 'class', 'slow-pulse-name-anim', 'Epic', 'A soft white name that pulses with a slow blue glow.', 'Elemental'),
('name_rainbow', 'Rainbow Shift', 'name_effect', 1800000, 'class', 'rainbow-text-anim', 'Epic', 'Animated rainbow text that cycles through the spectrum.', 'Spectrum'),
('name_flicker_neon', 'Flickering Neon', 'name_effect', 1800000, 'class', 'flicker-neon-anim', 'Epic', 'A teal neon sign effect with intermittent flicker.', NULL),
('name_shining_gold', 'Shining Gold Name', 'name_effect', 2500000, 'class', 'shining-gold-anim', 'Epic', 'An animated gold gradient that shimmers across the text.', 'Royal Metals'),
('name_pulsing_glow', 'Pulsing Glow', 'name_effect', 2500000, 'class', 'pulsing-glow-anim', 'Epic', 'A soft pulsing glow around your username.', NULL),
('name_matrix_rain', 'Matrix Rain', 'name_effect', 4500000, 'class', 'matrix-rain-anim', 'Mythic', 'Green matrix-style text rain for a cyber look.', NULL),
('name_holographic', 'Holographic', 'name_effect', 6000000, 'class', 'name_holographic', 'Mythic', 'A silver-cyan holographic sweep with a glossy shine.', 'Spectrum'),
('name_diamond_shimmer', 'Diamond Shimmer', 'name_effect', 6500000, 'class', 'diamond-shimmer-anim', 'Mythic', 'A diamond-white shimmer that slides across the text.', NULL),
('name_glitch_effect', 'Glitch Effect', 'name_effect', 9500000, 'class', 'glitch-anim', 'Mythic', 'A clean cyan-magenta glitch jitter across your name.', 'Voidwalker'),
('name_ocean_wave', 'Ocean Wave', 'name_effect', 11500000, 'class', 'ocean-wave-anim', 'Mythic', 'A blue wave gradient that moves across your name.', NULL),
('name_inferno', 'Inferno Name', 'name_effect', 13500000, 'class', 'inferno-name-anim', 'Mythic', 'A flame-like name effect with hot highlights.', NULL),
('name_sunset_blur', 'Sunset Blur', 'name_effect', 13500000, 'class', 'sunset-blur-anim', 'Mythic', 'A warm sunset gradient with a blurred glow.', NULL),
('name_void', 'Void Name', 'name_effect', 20000000, 'class', 'name_void', 'Mythic', 'A dim name rimmed by a cold void glow.', 'Voidwalker'),
('name_chroma', 'Chroma Name', 'name_effect', 25000000, 'class', 'chroma-name-anim', 'Mythic', 'A high-energy chroma sweep with the brightest spectral edge.', 'Chroma')
ON CONFLICT (item_key) DO UPDATE
SET name = EXCLUDED.name,
    slot = EXCLUDED.slot,
    cost = EXCLUDED.cost,
    css_type = EXCLUDED.css_type,
    css_value = EXCLUDED.css_value,
    rarity = EXCLUDED.rarity,
    description = EXCLUDED.description,
    collection = EXCLUDED.collection;

INSERT INTO public.meta (key, value)
VALUES ('shop_version', '2026-07-09T22:00:00Z')
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value;
