INSERT INTO public.shop_items (item_key, name, slot, cost, css_type, css_value, rarity, description) VALUES
('streak_freeze', 'Streak Freeze', 'consumable', 100000, 'text', 'Protects your streak if you miss a day.', 'Rare', 'Prevents one missed day from breaking your streak.'),
('reroll_shard', 'Reroll Shard', 'consumable', 200000, 'text', 'Allows you to reroll your daily color.', 'Rare', 'Adds 1 reroll shard for the daily results screen.'),
('frame_30_day', 'Monthly Grinder Frame', 'frame', 0, 'class', 'frame-streak-30', 'Mythic', 'Unlocked at a 30-day streak. A breathing emerald milestone frame.'),
('frame_100_day', 'Iron Will Frame', 'frame', 0, 'class', 'frame-streak-100', 'Mythic', 'Unlocked at a 100-day streak. A bright gold frame with a constant shine.'),
('frame_365_day', 'Annual Frame', 'frame', 0, 'class', 'frame-streak-365', 'Mythic', 'Unlocked at a 365-day streak. A prismatic anniversary frame with a full aura.'),
('frame_thin_white', 'Hairline Frame', 'frame', 40000, 'style', 'border: 1px solid rgba(255,255,255,0.35);', 'Common', 'A thin white outline around your name frame.'),
('frame_neon_cyan', 'Cyan Frame', 'frame', 125000, 'style', 'border: 1px solid #22d3ee; box-shadow: 0 0 12px rgba(34,211,238,0.5);', 'Rare', 'A cyan frame with a soft electric glow.'),
('frame_neon_pink', 'Pink Frame', 'frame', 125000, 'style', 'border: 1px solid #ff4fd8; box-shadow: 0 0 12px rgba(255,79,216,0.5);', 'Rare', 'A hot pink frame with a neon edge light.'),
('frame_gold_ring', 'Gold Ring', 'frame', 350000, 'style', 'border: 1px solid #f1c40f; box-shadow: 0 0 16px rgba(241,196,15,0.45);', 'Epic', 'A slim gold frame with a warm halo.'),
('frame_spectrum', 'Chroma Frame', 'frame', 3500000, 'class', 'frame-spectrum-anim', 'Mythic', 'A dark frame wrapped in a moving rainbow border.'),
('frame_diamond', 'Diamond Frame', 'frame', 9000000, 'class', 'frame-diamond-anim', 'Mythic', 'A white-blue frame with a fast crystal shimmer.'),
('border_neon', 'Neon Shell', 'profile_border', 180000, 'class', 'border-neon-anim', 'Rare', 'A violet profile border with a soft inner glow.'),
('border_prism', 'Prism Shell', 'profile_border', 450000, 'class', 'border-prism-anim', 'Epic', 'A clean pastel border with a light blush glow.'),
('border_gold', 'Golden Shell', 'profile_border', 900000, 'class', 'border-gold-anim', 'Epic', 'A rich gold border with a warm inset shine.'),
('border_crystal', 'Crystal Shell', 'profile_border', 1800000, 'class', 'border-crystal-anim', 'Epic', 'An icy blue border that brightens to white.'),
('border_celestial', 'Celestial Shell', 'profile_border', 3200000, 'class', 'border-celestial-anim', 'Mythic', 'A bright sky-glow border with a soft halo.'),
('border_chroma', 'Chroma Shell', 'profile_border', 5000000, 'class', 'border-chroma-anim', 'Mythic', 'A rainbow border that cycles through six colors.'),
('border_glitch', 'Signal Break', 'profile_border', 7500000, 'class', 'border-glitch-anim', 'Mythic', 'A white border that flickers cyan and magenta.'),
('border_void', 'Void Shell', 'profile_border', 12000000, 'class', 'border-void-anim', 'Mythic', 'A blackened border with a heavy pulsing shadow.'),
('bg_aurora', 'Aurora Background', 'profile_bg', 900000, 'style', 'background-image: linear-gradient(135deg, #00c6ff, #0072ff); background-size: cover;', 'Rare', 'A cool blue gradient that washes across the profile card.'),
('bg_sunset', 'Sunset Background', 'profile_bg', 900000, 'style', 'background-image: linear-gradient(135deg, #ff9a9e, #fad0c4); background-size: cover;', 'Rare', 'A warm pink-orange gradient across the profile card.'),
('bg_matrix', 'Matrix Background', 'profile_bg', 2200000, 'style', 'background-color: #001100; background-image: linear-gradient(0deg, transparent 24%, rgba(0, 255, 0, .1) 25%, rgba(0, 255, 0, .1) 26%, transparent 27%, transparent 74%, rgba(0, 255, 0, .1) 75%, rgba(0, 255, 0, .1) 76%, transparent 77%, transparent), linear-gradient(90deg, transparent 24%, rgba(0, 255, 0, .1) 25%, rgba(0, 255, 0, .1) 26%, transparent 27%, transparent 74%, rgba(0, 255, 0, .1) 75%, rgba(0, 255, 0, .1) 76%, transparent 77%, transparent); background-size: 50px 50px;', 'Epic', 'A dark green grid with a digital matrix texture.'),
('bg_void', 'Void Background', 'profile_bg', 6500000, 'style', 'background-image: radial-gradient(circle, #1a1a1a, #000000); background-size: cover;', 'Mythic', 'A near-black profile background with a deep center fade.'),
('name_italic', 'Italic Font', 'name_effect', 25000, 'style', 'font-style: italic; color: #fff;', 'Common', 'A clean italic slant for your username.'),
('name_drop_shadow', 'Drop Shadow', 'name_effect', 35000, 'style', 'text-shadow: 2px 2px 4px #000; color: #fff;', 'Common', 'A dark shadow behind your username for extra contrast.'),
('name_smallcaps', 'Small Caps', 'name_effect', 60000, 'style', 'font-variant: small-caps; color: #fff; letter-spacing: 1px;', 'Uncommon', 'Small caps lettering with a little extra spacing.'),
('name_glow_blue', 'Blue Glow', 'name_effect', 100000, 'style', 'text-shadow: 0 0 10px #3498db; color: #fff;', 'Rare', 'White text with a blue outer glow.'),
('name_glow_green', 'Green Glow', 'name_effect', 100000, 'style', 'text-shadow: 0 0 10px #2ecc71; color: #fff;', 'Rare', 'White text with a green neon edge.'),
('name_glow_purple', 'Purple Glow', 'name_effect', 100000, 'style', 'text-shadow: 0 0 10px #9b59b6; color: #fff;', 'Rare', 'White text with a soft purple glow.'),
('name_glow_red', 'Red Glow', 'name_effect', 100000, 'style', 'text-shadow: 0 0 10px #ff4c4c; color: #fff;', 'Rare', 'White text with a bright red glow.'),
('name_glow_pink_neon', 'Neon Pink Glow', 'name_effect', 220000, 'style', 'text-shadow: 0 0 5px #ff00de, 0 0 10px #ff00de; color: #fff;', 'Rare', 'White text with a stacked neon pink glow.'),
('name_gradient_purple', 'Purple Gradient', 'name_effect', 350000, 'style', 'background: linear-gradient(45deg, #8E2DE2, #4A00E0); -webkit-background-clip: text; background-clip: text; color: transparent;', 'Epic', 'A purple gradient clipped directly into your name.'),
('name_glow_gold', 'Gold Glow', 'name_effect', 450000, 'style', 'text-shadow: 0 0 15px #f1c40f; color: #fff;', 'Epic', 'White text with a strong gold halo.'),
('name_gradient_fire', 'Fire Gradient', 'name_effect', 550000, 'style', 'background: linear-gradient(45deg, #f12711, #f5af19); -webkit-background-clip: text; background-clip: text; color: transparent;', 'Epic', 'A red-orange gradient clipped into your name.'),
('name_rainbow', 'Rainbow Shift', 'name_effect', 1800000, 'class', 'rainbow-text-anim', 'Epic', 'Your name cycles through the rainbow one color at a time.'),
('name_flicker_neon', 'Flickering Neon', 'name_effect', 1800000, 'class', 'flicker-neon-anim', 'Epic', 'A teal neon sign effect with intermittent flicker.'),
('name_shining_gold', 'Shining Gold', 'name_effect', 2500000, 'class', 'shining-gold-anim', 'Epic', 'A gold gradient sweep that shimmers across your name.'),
('name_pulsing_glow', 'Pulsing Glow', 'name_effect', 2500000, 'class', 'pulsing-glow-anim', 'Epic', 'A white glow that slowly pulses violet.'),
('name_matrix_rain', 'Matrix Rain', 'name_effect', 4500000, 'class', 'matrix-rain-anim', 'Mythic', 'A green matrix gradient that scrolls through the text.'),
('name_diamond_shimmer', 'Diamond Shimmer', 'name_effect', 6500000, 'class', 'diamond-shimmer-anim', 'Mythic', 'A white-blue crystal shimmer sliding across your name.'),
('name_glitch_effect', 'Glitch Effect', 'name_effect', 9000000, 'class', 'glitch-anim', 'Mythic', 'A white name with constant cyan-magenta glitch jitter.'),
('name_ocean_wave', 'Ocean Wave', 'name_effect', 10500000, 'class', 'ocean-wave-anim', 'Mythic', 'A moving blue wave gradient across your name.'),
('name_sunset_blur', 'Sunset Blur', 'name_effect', 12500000, 'class', 'sunset-blur-anim', 'Mythic', 'A warm sunset gradient with a soft blurred glow.'),
('name_inferno', 'Inferno Name', 'name_effect', 13500000, 'class', 'inferno-name-anim', 'Mythic', 'A flame-lit name with hot white, gold, and orange highlights.'),
('name_spectrum', 'Spectrum Name', 'name_effect', 20000000, 'class', 'name-spectrum-anim', 'Mythic', 'A full moving rainbow gradient with a bright spectral edge.'),
('roll_sparkles', 'Sparkle Aura', 'roll_effect', 400000, 'class', 'roll-sparkles-anim', 'Epic', 'A soft white aura around the roll orb.'),
('roll_inferno', 'Inferno Aura', 'roll_effect', 4500000, 'class', 'roll-inferno-anim', 'Mythic', 'A hot orange-red aura pulsing around the roll orb.'),
('roll_spectrum', 'Spectrum Aura', 'roll_effect', 11000000, 'class', 'roll-spectrum-anim', 'Mythic', 'A rotating rainbow aura around the roll orb.'),
('lb_glow', 'Blue Glow Row', 'lb_theme', 300000, 'class', 'lb-glow-theme', 'Rare', 'A dark leaderboard row with a blue glow and inset light.'),
('lb_frosted', 'Frosted Glass', 'lb_theme', 2500000, 'style', 'background: linear-gradient(90deg, rgba(195, 226, 255, 0.28), rgba(255,255,255,0.16), rgba(195, 226, 255, 0.28)); border: 1px solid rgba(230,245,255,0.58); box-shadow: inset 0 1px 0 rgba(255,255,255,0.4), inset 0 0 18px rgba(190,220,255,0.18), 0 12px 28px rgba(120,150,190,0.2), 0 0 0 1px rgba(210,235,255,0.18); backdrop-filter: blur(14px);', 'Epic', 'A bright frosted glass row with icy highlights and soft blur.'),
('lb_gold', 'Golden Row', 'lb_theme', 6500000, 'class', 'lb-gold-theme', 'Mythic', 'A bright gold row with dark text and a polished shine.'),
('lb_spectrum', 'Chroma Row', 'lb_theme', 18000000, 'class', 'lb-spectrum-theme', 'Mythic', 'A dark row wrapped in an animated rainbow border.'),
('lb_void', 'Void Row', 'lb_theme', 22000000, 'style', 'background: linear-gradient(90deg, rgba(4,4,7,0.98), rgba(16,16,24,0.96), rgba(4,4,7,0.98)); border: 1px solid rgba(34,34,45,0.95); box-shadow: inset 0 0 18px rgba(0,0,0,0.82), 0 0 26px rgba(0,0,0,0.7), 0 0 0 1px rgba(90,90,110,0.12);', 'Mythic', 'A near-black showcase row with a dense void shadow.')
ON CONFLICT (item_key) DO UPDATE
SET name = EXCLUDED.name,
    slot = EXCLUDED.slot,
    cost = EXCLUDED.cost,
    css_type = EXCLUDED.css_type,
    css_value = EXCLUDED.css_value,
    rarity = EXCLUDED.rarity,
    description = EXCLUDED.description;

INSERT INTO public.meta (key, value)
VALUES ('shop_version', '2026-07-09T21:30:00Z')
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value;
